#!/bin/bash

cd visiond; xterm -e ./visiond &
cd ..
sleep 1;
cd labjackd; xterm -geometry -0+0 -e ./labjackd &
cd ..
sleep 1;
cd nav/; xterm -geometry +0-0 -e ./nav &
cd ..
sleep 1;
#cd planner/; xterm -geometry 135-0-0 -e ./planner &
cd planner/; xterm -geometry -0-0 -e ./planner &
cd ..
