#!/bin/bash

cd src/visiond; xterm -e ./visiond &
cd ../..
sleep 1;
cd src/labjackd; xterm -geometry -0+0 -e ./labjackd &
cd ../..
sleep 1;
cd src/nav/; xterm -geometry +0-0 -e ./nav &
cd ../..
sleep 1;
#cd src/planner/; xterm -geometry 135-0-0 -e ./planner &
cd src/planner/; xterm -geometry -0-0 -e ./planner &
cd ../..
