/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:
  double predict(void **attr, double *ret)
The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.
Specifically, these pointers are:
     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V
The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).
These scores correspond to the classes as follows:
            index       class name
           ------------------------
               0        non-buoy
               1        buoy
This classifier was automatically generated by jboost on
Thu Jan 07 14:09:25 PST 2010.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <values.h>
#include "strlcpy.h"
typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))
#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};
static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;
static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}
#define more_tokens()  (cur_word <= num_words - pattern_len)
#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}
static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;
  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);
  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}
static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;
  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }
  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= MAXINT - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}
double predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;
  Prediction_t p;
  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }
  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;
    while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen((char*)attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }
  reset_pred();
  add_pred(   /* R */
             -0.5367306788795341);
  if (defined_attr(0)) {  /* R.0 */
    if (double_attr(0) <= 84.5) {
      add_pred(   /* R.0:0 */
                 -1.4262803779615625);
      if (defined_attr(1)) {  /* R.0:0.0 */
        if (double_attr(1) <= 35.5) {
          add_pred(   /* R.0:0.0:0 */
                     0.20001778275359397);
        } else {
          add_pred(   /* R.0:0.0:1 */
                     -1.4186534526602732);
          if (defined_attr(0)) {  /* R.0:0.0:1.0 */
            if (double_attr(0) <= 28.5) {
              add_pred(   /* R.0:0.0:1.0:0 */
                         0.09275539806250271);
            } else {
              add_pred(   /* R.0:0.0:1.0:1 */
                         -0.5663492637766663);
              if (defined_attr(1)) {  /* R.0:0.0:1.0:1.0 */
                if (double_attr(1) <= 48.5) {
                  add_pred(   /* R.0:0.0:1.0:1.0:0 */
                             -0.18163844621671893);
                } else {
                  add_pred(   /* R.0:0.0:1.0:1.0:1 */
                             -2.735547364525497);
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.0:0.0:1.1 */
            if (double_attr(1) <= 42.5) {
              add_pred(   /* R.0:0.0:1.1:0 */
                         0.22225790181352698);
            } else {
              add_pred(   /* R.0:0.0:1.1:1 */
                         -0.09753585079427372);
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.0:0.1 */
        if (double_attr(2) <= 130.5) {
          add_pred(   /* R.0:0.1:0 */
                     0.4378581505103074);
          if (defined_attr(1)) {  /* R.0:0.1:0.0 */
            if (double_attr(1) <= 70.5) {
              add_pred(   /* R.0:0.1:0.0:0 */
                         0.2768404915426386);
            } else {
              add_pred(   /* R.0:0.1:0.0:1 */
                         -3.3374587548986603);
            }
          }
        } else {
          add_pred(   /* R.0:0.1:1 */
                     -0.7902878301981616);
          if (defined_attr(2)) {  /* R.0:0.1:1.0 */
            if (double_attr(2) <= 134.5) {
              add_pred(   /* R.0:0.1:1.0:0 */
                         0.4494232706881496);
              if (defined_attr(1)) {  /* R.0:0.1:1.0:0.0 */
                if (double_attr(1) <= 23.5) {
                  add_pred(   /* R.0:0.1:1.0:0.0:0 */
                             0.6556167010325231);
                } else {
                  add_pred(   /* R.0:0.1:1.0:0.0:1 */
                             0.01644639908626432);
                }
              }
            } else {
              add_pred(   /* R.0:0.1:1.0:1 */
                         -0.06117206659931591);
            }
          }
        }
      }
      if (defined_attr(1)) {  /* R.0:0.2 */
        if (double_attr(1) <= 51.5) {
          add_pred(   /* R.0:0.2:0 */
                     0.19065708077635385);
        } else {
          add_pred(   /* R.0:0.2:1 */
                     -1.2348114354219264);
        }
      }
      if (defined_attr(2)) {  /* R.0:0.3 */
        if (double_attr(2) <= 127.5) {
          add_pred(   /* R.0:0.3:0 */
                     0.38795674702625843);
          if (defined_attr(0)) {  /* R.0:0.3:0.0 */
            if (double_attr(0) <= 27.5) {
              add_pred(   /* R.0:0.3:0.0:0 */
                         0.22858163193132608);
            } else {
              add_pred(   /* R.0:0.3:0.0:1 */
                         -0.1114852275426769);
            }
          }
          if (defined_attr(0)) {  /* R.0:0.3:0.1 */
            if (double_attr(0) <= 45.5) {
              add_pred(   /* R.0:0.3:0.1:0 */
                         0.0709299111469088);
            } else {
              add_pred(   /* R.0:0.3:0.1:1 */
                         -0.49688607543784635);
              if (defined_attr(1)) {  /* R.0:0.3:0.1:1.0 */
                if (double_attr(1) <= 23.5) {
                  add_pred(   /* R.0:0.3:0.1:1.0:0 */
                             -0.15108278492852717);
                } else {
                  add_pred(   /* R.0:0.3:0.1:1.0:1 */
                             -2.5513313764249963);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.3:1 */
                     -0.28847996735666964);
          if (defined_attr(1)) {  /* R.0:0.3:1.0 */
            if (double_attr(1) <= 46.5) {
              add_pred(   /* R.0:0.3:1.0:0 */
                         0.03650084374448059);
            } else {
              add_pred(   /* R.0:0.3:1.0:1 */
                         -0.7470680559522976);
            }
          }
          if (defined_attr(0)) {  /* R.0:0.3:1.1 */
            if (double_attr(0) <= 32.5) {
              add_pred(   /* R.0:0.3:1.1:0 */
                         -0.20308057265359658);
              if (defined_attr(2)) {  /* R.0:0.3:1.1:0.0 */
                if (double_attr(2) <= 254.5) {
                  add_pred(   /* R.0:0.3:1.1:0.0:0 */
                             0.008348975052547435);
                } else {
                  add_pred(   /* R.0:0.3:1.1:0.0:1 */
                             -1.4112237611597314);
                  if (defined_attr(1)) {  /* R.0:0.3:1.1:0.0:1.0 */
                    if (double_attr(1) <= 10.5) {
                      add_pred(   /* R.0:0.3:1.1:0.0:1.0:0 */
                                 0.10481165712893892);
                    } else {
                      add_pred(   /* R.0:0.3:1.1:0.0:1.0:1 */
                                 -2.789717008993086);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:0.3:1.1:1 */
                         0.19380806285081573);
              if (defined_attr(1)) {  /* R.0:0.3:1.1:1.0 */
                if (double_attr(1) <= 5.5) {
                  add_pred(   /* R.0:0.3:1.1:1.0:0 */
                             -0.36047344587225494);
                  if (defined_attr(1)) {  /* R.0:0.3:1.1:1.0:0.0 */
                    if (double_attr(1) <= 2.5) {
                      add_pred(   /* R.0:0.3:1.1:1.0:0.0:0 */
                                 0.8672461329459663);
                    } else {
                      add_pred(   /* R.0:0.3:1.1:1.0:0.0:1 */
                                 -0.40776075815325374);
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:0.3:1.1:1.0:0.1 */
                    if (double_attr(0) <= 71.0) {
                      add_pred(   /* R.0:0.3:1.1:1.0:0.1:0 */
                                 0.34446665505400537);
                    } else {
                      add_pred(   /* R.0:0.3:1.1:1.0:0.1:1 */
                                 -0.36763912891066186);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.3:1.1:1.0:1 */
                             0.4597081622220671);
                  if (defined_attr(0)) {  /* R.0:0.3:1.1:1.0:1.0 */
                    if (double_attr(0) <= 76.5) {
                      add_pred(   /* R.0:0.3:1.1:1.0:1.0:0 */
                                 -0.1442471135478867);
                    } else {
                      add_pred(   /* R.0:0.3:1.1:1.0:1.0:1 */
                                 0.6056769442307434);
                      if (defined_attr(2)) {  /* R.0:0.3:1.1:1.0:1.0:1.0 */
                        if (double_attr(2) <= 254.5) {
                          add_pred(   /* R.0:0.3:1.1:1.0:1.0:1.0:0 */
                                     -0.1925624587299882);
                        } else {
                          add_pred(   /* R.0:0.3:1.1:1.0:1.0:1.0:1 */
                                     0.47471703151229455);
                          if (defined_attr(1)) {  /* R.0:0.3:1.1:1.0:1.0:1.0:1.0 */
                            if (double_attr(1) <= 7.5) {
                              add_pred(   /* R.0:0.3:1.1:1.0:1.0:1.0:1.0:0 */
                                         0.04296115481298153);
                            } else {
                              add_pred(   /* R.0:0.3:1.1:1.0:1.0:1.0:1.0:1 */
                                         1.1381558193819277);
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      if (defined_attr(1)) {  /* R.0:0.4 */
        if (double_attr(1) <= 29.5) {
          add_pred(   /* R.0:0.4:0 */
                     0.33010227130540115);
          if (defined_attr(2)) {  /* R.0:0.4:0.0 */
            if (double_attr(2) <= 102.5) {
              add_pred(   /* R.0:0.4:0.0:0 */
                         -1.6720731154564659);
            } else {
              add_pred(   /* R.0:0.4:0.0:1 */
                         0.12907809448085722);
            }
          }
        } else {
          add_pred(   /* R.0:0.4:1 */
                     -0.26211791706994764);
          if (defined_attr(0)) {  /* R.0:0.4:1.0 */
            if (double_attr(0) <= 15.5) {
              add_pred(   /* R.0:0.4:1.0:0 */
                         -3.897344269346778);
            } else {
              add_pred(   /* R.0:0.4:1.0:1 */
                         -0.03509678167936077);
              if (defined_attr(0)) {  /* R.0:0.4:1.0:1.0 */
                if (double_attr(0) <= 30.5) {
                  add_pred(   /* R.0:0.4:1.0:1.0:0 */
                             0.10427766333145258);
                  if (defined_attr(2)) {  /* R.0:0.4:1.0:1.0:0.0 */
                    if (double_attr(2) <= 138.5) {
                      add_pred(   /* R.0:0.4:1.0:1.0:0.0:0 */
                                 0.13628652811961117);
                    } else {
                      add_pred(   /* R.0:0.4:1.0:1.0:0.0:1 */
                                 -0.8078714783525983);
                    }
                  }
                  if (defined_attr(2)) {  /* R.0:0.4:1.0:1.0:0.1 */
                    if (double_attr(2) <= 111.5) {
                      add_pred(   /* R.0:0.4:1.0:1.0:0.1:0 */
                                 0.4104213323230987);
                      if (defined_attr(1)) {  /* R.0:0.4:1.0:1.0:0.1:0.0 */
                        if (double_attr(1) <= 61.5) {
                          add_pred(   /* R.0:0.4:1.0:1.0:0.1:0.0:0 */
                                     0.2789064973800681);
                        } else {
                          add_pred(   /* R.0:0.4:1.0:1.0:0.1:0.0:1 */
                                     -0.5515625582745649);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.4:1.0:1.0:0.1:1 */
                                 -0.06961457815647262);
                      if (defined_attr(1)) {  /* R.0:0.4:1.0:1.0:0.1:1.0 */
                        if (double_attr(1) <= 58.5) {
                          add_pred(   /* R.0:0.4:1.0:1.0:0.1:1.0:0 */
                                     0.005260678393341423);
                        } else {
                          add_pred(   /* R.0:0.4:1.0:1.0:0.1:1.0:1 */
                                     -1.2978495314335223);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.4:1.0:1.0:1 */
                             -1.106489078372102);
                  if (defined_attr(0)) {  /* R.0:0.4:1.0:1.0:1.0 */
                    if (double_attr(0) <= 36.5) {
                      add_pred(   /* R.0:0.4:1.0:1.0:1.0:0 */
                                 -0.3952485044192311);
                    } else {
                      add_pred(   /* R.0:0.4:1.0:1.0:1.0:1 */
                                 -3.1333660083922172);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(2)) {  /* R.0:0.4:1.1 */
            if (double_attr(2) <= 160.5) {
              add_pred(   /* R.0:0.4:1.1:0 */
                         0.005642275484852412);
            } else {
              add_pred(   /* R.0:0.4:1.1:1 */
                         -2.4850786992588794);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 0.6400693156568051);
      if (defined_attr(1)) {  /* R.0:1.0 */
        if (double_attr(1) <= 39.5) {
          add_pred(   /* R.0:1.0:0 */
                     -0.3033021824978577);
          if (defined_attr(2)) {  /* R.0:1.0:0.0 */
            if (double_attr(2) <= 253.5) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -0.8431743266146196);
              if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(2) <= 134.5) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             0.4279987294885292);
                  if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0:0.0 */
                    if (double_attr(1) <= 8.5) {
                      add_pred(   /* R.0:1.0:0.0:0.0:0.0:0 */
                                 0.4520679558604376);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.0:0.0:1 */
                                 -0.06959683856709101);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             -0.7670226763012723);
                  if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0:1.0 */
                    if (double_attr(1) <= 24.5) {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.0:0 */
                                 -0.7829621487465865);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.0:1 */
                                 0.38225168642483265);
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.0:1.0 */
                        if (double_attr(2) <= 237.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:0 */
                                     -0.03059762810930282);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1 */
                                     1.580193481753187);
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.1 */
                    if (double_attr(2) <= 250.5) {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.1:0 */
                                 -0.5338089953304369);
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.1:0.0 */
                        if (double_attr(2) <= 154.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.0:0 */
                                     0.2909807665556504);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.0:1 */
                                     -0.8665410147100132);
                          if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.1:0.0:1.0 */
                            if (double_attr(2) <= 245.5) {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.0:1.0:0 */
                                         -0.47349233001682184);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.0:1.0:1 */
                                         0.8226226561695467);
                            }
                          }
                        }
                      }
                      if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0:1.1:0.1 */
                        if (double_attr(1) <= 33.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.1:0 */
                                     -0.49836915436589757);
                          if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.1:0.1:0.0 */
                            if (double_attr(2) <= 146.5) {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.1:0.0:0 */
                                         0.19986568319490053);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.1:0.0:1 */
                                         -0.6314110482230202);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:0.1:1 */
                                     0.8139240066426522);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.1:1 */
                                 0.7219480410908756);
                      if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0:1.1:1.0 */
                        if (double_attr(1) <= 12.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:1.0:0 */
                                     -0.5446005992157488);
                          if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.1:1.0:0.0 */
                            if (double_attr(2) <= 252.5) {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:1.0:0.0:0 */
                                         -1.318072386443587);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:0.0:1.1:1.0:0.0:1 */
                                         0.019285220088878355);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:1.1:1.0:1 */
                                     1.4964054837837226);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:0.1 */
                if (double_attr(1) <= 29.5) {
                  add_pred(   /* R.0:1.0:0.0:0.1:0 */
                             -0.05903627538436399);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.1:1 */
                             0.3327967718239191);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:0.1:1.0 */
                    if (double_attr(0) <= 101.5) {
                      add_pred(   /* R.0:1.0:0.0:0.1:1.0:0 */
                                 -0.8190502867004877);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.1:1.0:1 */
                                 0.28481000675096807);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         0.26258317076573134);
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0 */
                if (double_attr(1) <= 13.5) {
                  add_pred(   /* R.0:1.0:0.0:1.0:0 */
                             -0.2705014326590217);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:0.0 */
                    if (double_attr(0) <= 112.5) {
                      add_pred(   /* R.0:1.0:0.0:1.0:0.0:0 */
                                 -0.1354296799586258);
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:1.0:0.0:0.0 */
                        if (double_attr(2) <= 254.5) {
                          add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:0 */
                                     0.19665733337345534);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:1 */
                                     -0.1983430902279536);
                          if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:0.0:0.0:1.0 */
                            if (double_attr(0) <= 88.5) {
                              add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:1.0:0 */
                                         0.4413254736923972);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:1.0:1 */
                                         -0.18528749509402315);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:0.0:0.0:1.0:1.0 */
                                if (double_attr(0) <= 111.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:1.0:1.0:0 */
                                             -0.07494881383560428);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.0:0.0:0.0:1.0:1.0:1 */
                                             -0.9421269606713867);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.0:0.0:1 */
                                 0.17526134751044442);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:0.0:1.0 */
                        if (double_attr(0) <= 131.5) {
                          add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:0 */
                                     0.21665556033633954);
                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0:0.0:1.0:0.0 */
                            if (double_attr(1) <= 6.5) {
                              add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:0.0:0 */
                                         0.34701897356347555);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:0.0:1 */
                                         -0.03723858650799851);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:0.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 124.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:0.0:1.0:0 */
                                             0.02503070322061027);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:0.0:1.0:1 */
                                             -2.549963229143829);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.0:0.0:1.0:1 */
                                     -0.4798367928591953);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.0:1 */
                             1.3808283485614001);
                  if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0:1.0 */
                    if (double_attr(1) <= 27.5) {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:0 */
                                 0.06964494010997552);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:1 */
                                 3.1388602906582355);
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1 */
                if (double_attr(1) <= 9.5) {
                  add_pred(   /* R.0:1.0:0.0:1.1:0 */
                             -0.313451935750169);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.1:1 */
                             0.5244049164503346);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0 */
                    if (double_attr(0) <= 92.5) {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0 */
                                 0.6376192971119478);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:1 */
                                 -0.10840828156523163);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:1.0 */
                        if (double_attr(0) <= 104.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0 */
                                     -0.3684711916195622);
                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:1.0:1.0:0.0 */
                            if (double_attr(1) <= 18.5) {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:0 */
                                         -0.39817682056511966);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:1 */
                                         0.7992462185235771);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:1 */
                                     0.13459663290783994);
                        }
                      }
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.1 */
                    if (double_attr(0) <= 117.5) {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.1:0 */
                                 0.06006831130698643);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.1:1 */
                                 -0.5647047604139104);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.1:1.0 */
                        if (double_attr(0) <= 137.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.1:1.0:0 */
                                     -0.9094520623809682);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.1:1.0:1 */
                                     0.47846470523220375);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     2.2255444285476114);
          if (defined_attr(2)) {  /* R.0:1.0:1.0 */
            if (double_attr(2) <= 112.5) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -1.7412641970335279);
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         1.0773350773782924);
              if (defined_attr(1)) {  /* R.0:1.0:1.0:1.0 */
                if (double_attr(1) <= 100.5) {
                  add_pred(   /* R.0:1.0:1.0:1.0:0 */
                             0.17148774599998473);
                  if (defined_attr(0)) {  /* R.0:1.0:1.0:1.0:0.0 */
                    if (double_attr(0) <= 172.5) {
                      add_pred(   /* R.0:1.0:1.0:1.0:0.0:0 */
                                 -0.004427837268062572);
                      if (defined_attr(0)) {  /* R.0:1.0:1.0:1.0:0.0:0.0 */
                        if (double_attr(0) <= 127.5) {
                          add_pred(   /* R.0:1.0:1.0:1.0:0.0:0.0:0 */
                                     -0.2265314237543249);
                        } else {
                          add_pred(   /* R.0:1.0:1.0:1.0:0.0:0.0:1 */
                                     2.6841916408243653);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:1.0:1.0:0.0:1 */
                                 -2.5629238804707892);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:1.0:1.0:1 */
                             3.8946180910963712);
                }
              }
            }
          }
          if (defined_attr(0)) {  /* R.0:1.0:1.1 */
            if (double_attr(0) <= 106.5) {
              add_pred(   /* R.0:1.0:1.1:0 */
                         -1.2665363078700682);
              if (defined_attr(2)) {  /* R.0:1.0:1.1:0.0 */
                if (double_attr(2) <= 231.5) {
                  add_pred(   /* R.0:1.0:1.1:0.0:0 */
                             -1.4982202065135513);
                  if (defined_attr(0)) {  /* R.0:1.0:1.1:0.0:0.0 */
                    if (double_attr(0) <= 100.5) {
                      add_pred(   /* R.0:1.0:1.1:0.0:0.0:0 */
                                 -2.7262093240684493);
                      if (defined_attr(0)) {  /* R.0:1.0:1.1:0.0:0.0:0.0 */
                        if (double_attr(0) <= 93.5) {
                          add_pred(   /* R.0:1.0:1.1:0.0:0.0:0.0:0 */
                                     -2.3914978384760492);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:0.0:0.0:0.0:1 */
                                     -1.2937555719604095);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:1.1:0.0:0.0:1 */
                                 0.28489365762303676);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:1.1:0.0:1 */
                             2.81820476213945);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.1:1 */
                         0.17015957096332834);
              if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0 */
                if (double_attr(2) <= 149.5) {
                  add_pred(   /* R.0:1.0:1.1:1.0:0 */
                             -0.4648064935737705);
                } else {
                  add_pred(   /* R.0:1.0:1.1:1.0:1 */
                             1.0990620219713425);
                  if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0 */
                    if (double_attr(1) <= 52.5) {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:0 */
                                 -0.14192280111371136);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:1 */
                                 2.6146297545923005);
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:1.1:1.1 */
                if (double_attr(1) <= 83.5) {
                  add_pred(   /* R.0:1.0:1.1:1.1:0 */
                             -0.3094970960789043);
                } else {
                  add_pred(   /* R.0:1.0:1.1:1.1:1 */
                             1.1803744535955547);
                }
              }
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.0:1.1 */
        if (double_attr(0) <= 117.5) {
          add_pred(   /* R.0:1.1:0 */
                     0.29347641987675194);
          if (defined_attr(1)) {  /* R.0:1.1:0.0 */
            if (double_attr(1) <= 7.5) {
              add_pred(   /* R.0:1.1:0.0:0 */
                         -1.054747983518315);
              if (defined_attr(0)) {  /* R.0:1.1:0.0:0.0 */
                if (double_attr(0) <= 101.0) {
                  add_pred(   /* R.0:1.1:0.0:0.0:0 */
                             0.14306267504475312);
                  if (defined_attr(0)) {  /* R.0:1.1:0.0:0.0:0.0 */
                    if (double_attr(0) <= 95.5) {
                      add_pred(   /* R.0:1.1:0.0:0.0:0.0:0 */
                                 -0.08162014947466113);
                      if (defined_attr(2)) {  /* R.0:1.1:0.0:0.0:0.0:0.0 */
                        if (double_attr(2) <= 254.5) {
                          add_pred(   /* R.0:1.1:0.0:0.0:0.0:0.0:0 */
                                     0.1462403076847704);
                        } else {
                          add_pred(   /* R.0:1.1:0.0:0.0:0.0:0.0:1 */
                                     -0.38803230542473993);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.1:0.0:0.0:0.0:1 */
                                 0.32888751171493585);
                      if (defined_attr(1)) {  /* R.0:1.1:0.0:0.0:0.0:1.0 */
                        if (double_attr(1) <= 4.5) {
                          add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:0 */
                                     -0.19668531756098315);
                          if (defined_attr(2)) {  /* R.0:1.1:0.0:0.0:0.0:1.0:0.0 */
                            if (double_attr(2) <= 254.5) {
                              add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:0.0:0 */
                                         -0.7764508178414427);
                            } else {
                              add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:0.0:1 */
                                         0.254833254532017);
                              if (defined_attr(0)) {  /* R.0:1.1:0.0:0.0:0.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 98.5) {
                                  add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:0.0:1.0:0 */
                                             -2.469063244620045);
                                } else {
                                  add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:0.0:1.0:1 */
                                             0.31919935118503967);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:0.0:0.0:0.0:1.0:1 */
                                     0.38988091541593556);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:0.0:0.0:1 */
                             -0.32690790985309465);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:0.0:1 */
                         0.5012301081391337);
              if (defined_attr(2)) {  /* R.0:1.1:0.0:1.0 */
                if (double_attr(2) <= 99.5) {
                  add_pred(   /* R.0:1.1:0.0:1.0:0 */
                             -2.127546171677788);
                } else {
                  add_pred(   /* R.0:1.1:0.0:1.0:1 */
                             0.1732652599547844);
                  if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0 */
                    if (double_attr(0) <= 107.5) {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:0 */
                                 -0.13350383705449007);
                    } else {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:1 */
                                 0.2949159192553204);
                      if (defined_attr(2)) {  /* R.0:1.1:0.0:1.0:1.0:1.0 */
                        if (double_attr(2) <= 240.5) {
                          add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0 */
                                     -0.16178193048973807);
                          if (defined_attr(1)) {  /* R.0:1.1:0.0:1.0:1.0:1.0:0.0 */
                            if (double_attr(1) <= 21.5) {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:0 */
                                         -0.6124707493593439);
                            } else {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:1 */
                                         0.07696612003485158);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1 */
                                     0.1516068820399752);
                          if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0:1.0:1.0 */
                            if (double_attr(0) <= 115.5) {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1.0:0 */
                                         0.15447255181491715);
                            } else {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1.0:1 */
                                         -0.5523171314569721);
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.1:1 */
                     -1.2533566653425172);
          if (defined_attr(0)) {  /* R.0:1.1:1.0 */
            if (double_attr(0) <= 123.5) {
              add_pred(   /* R.0:1.1:1.0:0 */
                         0.40863952786592694);
              if (defined_attr(1)) {  /* R.0:1.1:1.0:0.0 */
                if (double_attr(1) <= 4.5) {
                  add_pred(   /* R.0:1.1:1.0:0.0:0 */
                             -2.7388466408538212);
                } else {
                  add_pred(   /* R.0:1.1:1.0:0.0:1 */
                             0.1704339847535984);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:1.0:1 */
                         -0.4909001262882847);
            }
          }
        }
      }
    }
  }
  if (defined_attr(1)) {  /* R.1 */
    if (double_attr(1) <= 5.5) {
      add_pred(   /* R.1:0 */
                 -0.3197931245008842);
      if (defined_attr(0)) {  /* R.1:0.0 */
        if (double_attr(0) <= 47.5) {
          add_pred(   /* R.1:0.0:0 */
                     0.5110628535669262);
          if (defined_attr(2)) {  /* R.1:0.0:0.0 */
            if (double_attr(2) <= 253.5) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         -0.17233480510932495);
              if (defined_attr(2)) {  /* R.1:0.0:0.0:0.0 */
                if (double_attr(2) <= 120.5) {
                  add_pred(   /* R.1:0.0:0.0:0.0:0 */
                             0.3139715731121161);
                } else {
                  add_pred(   /* R.1:0.0:0.0:0.0:1 */
                             -0.5539845661910199);
                }
              }
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         0.8822084437808747);
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     -0.2507036590142773);
          if (defined_attr(2)) {  /* R.1:0.0:1.0 */
            if (double_attr(2) <= 128.5) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         1.2270365478963778);
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         -0.20371416029363978);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 0.10952916027749347);
      if (defined_attr(0)) {  /* R.1:1.0 */
        if (double_attr(0) <= 18.5) {
          add_pred(   /* R.1:1.0:0 */
                     -0.4512757910058349);
          if (defined_attr(1)) {  /* R.1:1.0:0.0 */
            if (double_attr(1) <= 20.5) {
              add_pred(   /* R.1:1.0:0.0:0 */
                         0.290083668477191);
            } else {
              add_pred(   /* R.1:1.0:0.0:1 */
                         -0.7628027699094949);
              if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0 */
                if (double_attr(0) <= 13.5) {
                  add_pred(   /* R.1:1.0:0.0:1.0:0 */
                             -2.0278341403006808);
                } else {
                  add_pred(   /* R.1:1.0:0.0:1.0:1 */
                             -0.25903841376378145);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.1:1.0:1 */
                     0.07407478462769045);
          if (defined_attr(0)) {  /* R.1:1.0:1.0 */
            if (double_attr(0) <= 123.5) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         0.05399972161939138);
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         -0.3971223192821915);
            }
          }
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.2 */
    if (double_attr(2) <= 91.5) {
      add_pred(   /* R.2:0 */
                 -1.292059011998976);
    } else {
      add_pred(   /* R.2:1 */
                 0.03215012231170814);
    }
  }
  return finalize_pred();
}
