/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:
  double predict(void **attr, double *ret)
The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.
Specifically, these pointers are:
     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V
The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).
These scores correspond to the classes as follows:
            index       class name
           ------------------------
               0        non-buoy
               1        buoy
This classifier was automatically generated by jboost on
Tue Feb 02 13:49:45 PST 2010.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <values.h>
#include "strlcpy.h"
typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))
#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};
static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;
static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}
#define more_tokens()  (cur_word <= num_words - pattern_len)
#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}
static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;
  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);
  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}
static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;
  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }
  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= MAXINT - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}
double predict_transdec(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;
  Prediction_t p;
  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }
  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;
    while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen((char*)attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }
  reset_pred();
  add_pred(   /* R */
             -0.5080487452193705);
  if (defined_attr(0)) {  /* R.0 */
    if (double_attr(0) <= 76.5) {
      add_pred(   /* R.0:0 */
                 -3.0234957534611397);
      if (defined_attr(1)) {  /* R.0:0.0 */
        if (double_attr(1) <= 25.5) {
          add_pred(   /* R.0:0.0:0 */
                     0.00717524579383596);
        } else {
          add_pred(   /* R.0:0.0:1 */
                     -3.3398495053400117);
        }
      }
      if (defined_attr(2)) {  /* R.0:0.1 */
        if (double_attr(2) <= 178.5) {
          add_pred(   /* R.0:0.1:0 */
                     -1.8248371699282016);
        } else {
          add_pred(   /* R.0:0.1:1 */
                     0.3915995733173943);
          if (defined_attr(1)) {  /* R.0:0.1:1.0 */
            if (double_attr(1) <= 10.5) {
              add_pred(   /* R.0:0.1:1.0:0 */
                         0.4693217073236615);
            } else {
              add_pred(   /* R.0:0.1:1.0:1 */
                         -0.7734030345778843);
              if (defined_attr(2)) {  /* R.0:0.1:1.0:1.0 */
                if (double_attr(2) <= 241.5) {
                  add_pred(   /* R.0:0.1:1.0:1.0:0 */
                             0.25401182054407495);
                } else {
                  add_pred(   /* R.0:0.1:1.0:1.0:1 */
                             -2.5749502103644706);
                }
              }
            }
          }
        }
      }
      if (defined_attr(1)) {  /* R.0:0.2 */
        if (double_attr(1) <= 2.5) {
          add_pred(   /* R.0:0.2:0 */
                     1.0721075032353817);
          if (defined_attr(0)) {  /* R.0:0.2:0.0 */
            if (double_attr(0) <= 60.0) {
              add_pred(   /* R.0:0.2:0.0:0 */
                         0.42031961812020313);
              if (defined_attr(0)) {  /* R.0:0.2:0.0:0.0 */
                if (double_attr(0) <= 37.5) {
                  add_pred(   /* R.0:0.2:0.0:0.0:0 */
                             -0.1216825026032625);
                } else {
                  add_pred(   /* R.0:0.2:0.0:0.0:1 */
                             0.7831141601714234);
                }
              }
              if (defined_attr(2)) {  /* R.0:0.2:0.0:0.1 */
                if (double_attr(2) <= 253.5) {
                  add_pred(   /* R.0:0.2:0.0:0.1:0 */
                             -0.5481220835468525);
                } else {
                  add_pred(   /* R.0:0.2:0.0:0.1:1 */
                             0.28079623384500074);
                }
              }
            } else {
              add_pred(   /* R.0:0.2:0.0:1 */
                         -2.126264125616268);
            }
          }
        } else {
          add_pred(   /* R.0:0.2:1 */
                     -0.46647772672378796);
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 0.7125451908492139);
      if (defined_attr(1)) {  /* R.0:1.0 */
        if (double_attr(1) <= 34.5) {
          add_pred(   /* R.0:1.0:0 */
                     -0.50579089144445);
          if (defined_attr(2)) {  /* R.0:1.0:0.0 */
            if (double_attr(2) <= 252.5) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -1.6096210814683032);
              if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(1) <= 30.5) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             -1.2679316893715753);
                  if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:0.0 */
                    if (double_attr(2) <= 248.5) {
                      add_pred(   /* R.0:1.0:0.0:0.0:0.0:0 */
                                 -0.8689459467244632);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:0.0:0.0:0.0 */
                        if (double_attr(0) <= 122.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:0.0:0.0:0 */
                                     -0.31015921311487654);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:0.0:0.0:1 */
                                     0.23141951048752296);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.0:0.0:1 */
                                 0.27890404551374864);
                      if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0:0.0:1.0 */
                        if (double_attr(1) <= 19.5) {
                          add_pred(   /* R.0:1.0:0.0:0.0:0.0:1.0:0 */
                                     -0.5576784940914381);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:0.0:0.0:1.0:1 */
                                     1.7940441596848151);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             0.5612895008644412);
                  if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0:1.0 */
                    if (double_attr(2) <= 212.5) {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.0:0 */
                                 -0.47916118995448503);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.0:1.0:1 */
                                 1.5020970358320402);
                    }
                  }
                }
              }
              if (defined_attr(0)) {  /* R.0:1.0:0.0:0.1 */
                if (double_attr(0) <= 138.5) {
                  add_pred(   /* R.0:1.0:0.0:0.1:0 */
                             -0.01537654812798639);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.1:1 */
                             1.0124832433810214);
                  if (defined_attr(2)) {  /* R.0:1.0:0.0:0.1:1.0 */
                    if (double_attr(2) <= 135.5) {
                      add_pred(   /* R.0:1.0:0.0:0.1:1.0:0 */
                                 -1.8487046729644048);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:0.1:1.0:1 */
                                 0.6447153146590194);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         0.24371353668856793);
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0 */
                if (double_attr(1) <= 13.5) {
                  add_pred(   /* R.0:1.0:0.0:1.0:0 */
                             -0.3470287552535559);
                  if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0:0.0 */
                    if (double_attr(1) <= 11.5) {
                      add_pred(   /* R.0:1.0:0.0:1.0:0.0:0 */
                                 -0.01183513647786481);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.0:0.0:1 */
                                 0.2969530319822543);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.0:1 */
                             1.2314455395761976);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0:1.0 */
                    if (double_attr(0) <= 105.5) {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:0 */
                                 -0.25932614234019336);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:1 */
                                 0.1908252427502393);
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1 */
                if (double_attr(1) <= 5.5) {
                  add_pred(   /* R.0:1.0:0.0:1.1:0 */
                             -0.6833758618080549);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0 */
                    if (double_attr(0) <= 87.0) {
                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:0 */
                                 -1.026628428231347);
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1:0.0:0.0 */
                        if (double_attr(2) <= 254.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:0.0:0 */
                                     -1.1376998308480055);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:0.0:1 */
                                     -0.733394019340239);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:1 */
                                 -0.1414150229740623);
                      if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:0.0:1.0 */
                        if (double_attr(1) <= 4.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0 */
                                     -0.15175568653991928);
                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:0.0 */
                            if (double_attr(1) <= 3.5) {
                              add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0 */
                                         -0.028726467196181067);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0 */
                                if (double_attr(0) <= 102.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0:0 */
                                             0.06337429365422262);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0:1 */
                                             -0.4478119163880314);
                                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0:1.0 */
                                    if (double_attr(0) <= 124.5) {
                                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0:1.0:0 */
                                                 -1.3866664008886096);
                                    } else {
                                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:0.0:1.0:1 */
                                                 -0.018112725790332622);
                                    }
                                  }
                                }
                              }
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:1 */
                                         -0.587713129414961);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 123.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:1.0:0 */
                                             -1.1184841473172902);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:0.0:1.0:1 */
                                             0.27555969858296886);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1 */
                                     0.3275326839054785);
                          if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:1.0 */
                            if (double_attr(0) <= 93.0) {
                              add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:0 */
                                         -1.392461992381356);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1 */
                                         0.21268104451955516);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0 */
                                if (double_attr(0) <= 99.0) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0:0 */
                                             0.29322160370099143);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0:1 */
                                             -0.15113371366414904);
                                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0:1.0 */
                                    if (double_attr(0) <= 111.0) {
                                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0:1.0:0 */
                                                 -2.0283264824007823);
                                    } else {
                                      add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.0:1.0:1.0:1.0:1 */
                                                 0.09309114376794449);
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:0.0:1.1 */
                        if (double_attr(0) <= 146.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.1:0 */
                                     0.04429085141665809);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:0.0:1.1:1 */
                                     -0.9255095912315264);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.1:1 */
                             0.26408256310713907);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0 */
                    if (double_attr(0) <= 123.5) {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0 */
                                 0.24180198782348622);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0 */
                        if (double_attr(0) <= 84.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0 */
                                     0.39033665202051016);
                          if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:0.0 */
                            if (double_attr(2) <= 254.5) {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0.0:0 */
                                         -1.0830082590719647);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0.0:1 */
                                         0.2702075194757591);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1 */
                                     0.0295155384077527);
                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0 */
                            if (double_attr(1) <= 9.5) {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0 */
                                         -0.12122156114386244);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0 */
                                if (double_attr(0) <= 118.0) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0 */
                                             -0.18392382291608067);
                                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.0 */
                                    if (double_attr(0) <= 114.0) {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.0:0 */
                                                 -0.09098474178588206);
                                    } else {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.0:1 */
                                                 -1.2175335797781626);
                                    }
                                  }
                                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1 */
                                    if (double_attr(0) <= 88.0) {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:0 */
                                                 0.17564837059755226);
                                    } else {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1 */
                                                 -0.16264277512712702);
                                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0 */
                                        if (double_attr(0) <= 94.5) {
                                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0:0 */
                                                     -1.1821132601655486);
                                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0:0.0 */
                                            if (double_attr(1) <= 7.5) {
                                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0:0.0:0 */
                                                         -2.0475924666478713);
                                            } else {
                                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0:0.0:1 */
                                                         -0.41318611141789724);
                                            }
                                          }
                                        } else {
                                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:0.1:1.0:1 */
                                                     0.002097830758336613);
                                        }
                                      }
                                    }
                                  }
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1 */
                                             0.5065474860531266);
                                  if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0 */
                                    if (double_attr(1) <= 6.5) {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0:0 */
                                                 0.4661498939278554);
                                    } else {
                                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0:1 */
                                                 -0.1278423181331853);
                                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0:1.0 */
                                        if (double_attr(0) <= 121.5) {
                                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0:1.0:0 */
                                                     -2.3584350040412985);
                                        } else {
                                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:0.0:1.0:1.0:1 */
                                                     0.09659699236951709);
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1 */
                                         0.17918034407213718);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.0 */
                                if (double_attr(0) <= 91.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.0:0 */
                                             0.43436098204835816);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.0:1 */
                                             -0.040352637933884446);
                                }
                              }
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.1 */
                                if (double_attr(0) <= 117.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.1:0 */
                                             0.04285139854379409);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1.0:1.1:1 */
                                             -0.7515122315420912);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:1 */
                                 -0.8805283905984068);
                      if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:1.0 */
                        if (double_attr(0) <= 142.5) {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0 */
                                     -0.5582246093928904);
                          if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1:1.0:1.0:0.0 */
                            if (double_attr(1) <= 7.5) {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:0 */
                                         0.12326624633176334);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:0.0 */
                                if (double_attr(0) <= 130.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:0.0:0 */
                                             0.41929191875539656);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:0.0:1 */
                                             -1.255465001277371);
                                }
                              }
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:1 */
                                         -0.5987417222784368);
                              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 134.5) {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:1.0:0 */
                                             -1.0240409693401467);
                                } else {
                                  add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:0.0:1.0:1 */
                                             0.24158108069816342);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:1.0:1 */
                                     0.20154471315751538);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.2 */
                if (double_attr(1) <= 27.5) {
                  add_pred(   /* R.0:1.0:0.0:1.2:0 */
                             -0.028016186050110657);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.2:1 */
                             2.920422749130174);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     2.1538624912567292);
          if (defined_attr(0)) {  /* R.0:1.0:1.0 */
            if (double_attr(0) <= 110.5) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -0.8026151241891396);
              if (defined_attr(2)) {  /* R.0:1.0:1.0:0.0 */
                if (double_attr(2) <= 231.5) {
                  add_pred(   /* R.0:1.0:1.0:0.0:0 */
                             -1.0158955638528069);
                } else {
                  add_pred(   /* R.0:1.0:1.0:0.0:1 */
                             3.5252258273455253);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         1.1691959530887526);
              if (defined_attr(0)) {  /* R.0:1.0:1.0:1.0 */
                if (double_attr(0) <= 112.5) {
                  add_pred(   /* R.0:1.0:1.0:1.0:0 */
                             -1.0967285670422529);
                } else {
                  add_pred(   /* R.0:1.0:1.0:1.0:1 */
                             0.10666298606819821);
                }
              }
            }
          }
          if (defined_attr(0)) {  /* R.0:1.0:1.1 */
            if (double_attr(0) <= 106.5) {
              add_pred(   /* R.0:1.0:1.1:0 */
                         -1.979958854603588);
            } else {
              add_pred(   /* R.0:1.0:1.1:1 */
                         0.535768356705358);
              if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0 */
                if (double_attr(2) <= 90.5) {
                  add_pred(   /* R.0:1.0:1.1:1.0:0 */
                             -1.7966480755636134);
                } else {
                  add_pred(   /* R.0:1.0:1.1:1.0:1 */
                             0.32122338676426754);
                  if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0 */
                    if (double_attr(1) <= 40.5) {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:0 */
                                 -0.8023122421498646);
                      if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0:1.0:0.0 */
                        if (double_attr(2) <= 204.5) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.0:0 */
                                     -0.8484454960777726);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.0:1 */
                                     1.104506061491327);
                        }
                      }
                      if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0:1.0:0.1 */
                        if (double_attr(2) <= 160.5) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.1:0 */
                                     -1.6426215041880563);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.1:1 */
                                     0.15865205110240702);
                        }
                      }
                      if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0:0.2 */
                        if (double_attr(1) <= 36.5) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.2:0 */
                                     -0.7912423548470902);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.2:1 */
                                     0.21384016025732247);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:1 */
                                 0.49799445930486996);
                      if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0:1.0:1.0 */
                        if (double_attr(2) <= 149.5) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:0 */
                                     0.0020893751200420064);
                          if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0:1.0:0.0 */
                            if (double_attr(1) <= 45.5) {
                              add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:0.0:0 */
                                         -1.1129439479567504);
                            } else {
                              add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:0.0:1 */
                                         -0.09580689560151534);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:1 */
                                     1.4494817298585299);
                        }
                      }
                      if (defined_attr(0)) {  /* R.0:1.0:1.1:1.0:1.0:1.1 */
                        if (double_attr(0) <= 174.5) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:0 */
                                     0.32284847049346543);
                          if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0:1.1:0.0 */
                            if (double_attr(1) <= 52.5) {
                              add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:0.0:0 */
                                         -0.4623459207441803);
                            } else {
                              add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:0.0:1 */
                                         0.6557063974285535);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:1 */
                                     -2.2588501532635297);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      if (defined_attr(1)) {  /* R.0:1.1 */
        if (double_attr(1) <= 7.5) {
          add_pred(   /* R.0:1.1:0 */
                     -0.975431195852502);
          if (defined_attr(0)) {  /* R.0:1.1:0.0 */
            if (double_attr(0) <= 77.5) {
              add_pred(   /* R.0:1.1:0.0:0 */
                         0.9259407832099903);
            } else {
              add_pred(   /* R.0:1.1:0.0:1 */
                         -0.10641128539404196);
            }
          }
        } else {
          add_pred(   /* R.0:1.1:1 */
                     0.33772805180249477);
          if (defined_attr(0)) {  /* R.0:1.1:1.0 */
            if (double_attr(0) <= 122.5) {
              add_pred(   /* R.0:1.1:1.0:0 */
                         0.6753872350145611);
              if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0 */
                if (double_attr(0) <= 108.5) {
                  add_pred(   /* R.0:1.1:1.0:0.0:0 */
                             -0.17433795547891748);
                  if (defined_attr(2)) {  /* R.0:1.1:1.0:0.0:0.0 */
                    if (double_attr(2) <= 227.5) {
                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:0 */
                                 -1.2574047059680689);
                      if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0:0.0 */
                        if (double_attr(0) <= 103.5) {
                          add_pred(   /* R.0:1.1:1.0:0.0:0.0:0.0:0 */
                                     -1.195003636890511);
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.0:0.0:0.0:1 */
                                     0.3082033264840447);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1 */
                                 0.0639392875108238);
                      if (defined_attr(1)) {  /* R.0:1.1:1.0:0.0:0.0:1.0 */
                        if (double_attr(1) <= 15.5) {
                          add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0 */
                                     -0.18682806354233775);
                          if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0:1.0:0.0 */
                            if (double_attr(0) <= 92.5) {
                              add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:0 */
                                         0.37642537011816496);
                            } else {
                              add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1 */
                                         -0.3581053365141887);
                              if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 107.5) {
                                  add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0 */
                                             -0.589101046522569);
                                  if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.0 */
                                    if (double_attr(0) <= 98.5) {
                                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.0:0 */
                                                 -0.7680341642717252);
                                    } else {
                                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.0:1 */
                                                 -0.13558158861680406);
                                    }
                                  }
                                  if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.1 */
                                    if (double_attr(0) <= 106.5) {
                                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.1:0 */
                                                 -0.07444843550943173);
                                    } else {
                                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:0.1:1 */
                                                 -2.182903218937569);
                                    }
                                  }
                                } else {
                                  add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:0.0:1.0:1 */
                                             0.772492906650404);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.0:0.0:1.0:1 */
                                     0.7728671111391002);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:1.0:0.0:1 */
                             0.31056070361549865);
                  if (defined_attr(1)) {  /* R.0:1.1:1.0:0.0:1.0 */
                    if (double_attr(1) <= 8.5) {
                      add_pred(   /* R.0:1.1:1.0:0.0:1.0:0 */
                                 -1.9446102090388055);
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.0:1.0:1 */
                                 0.12953786190351932);
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:1.1 */
                    if (double_attr(0) <= 119.5) {
                      add_pred(   /* R.0:1.1:1.0:0.0:1.1:0 */
                                 0.08884572273464944);
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.0:1.1:1 */
                                 -0.601111487731317);
                      if (defined_attr(2)) {  /* R.0:1.1:1.0:0.0:1.1:1.0 */
                        if (double_attr(2) <= 233.5) {
                          add_pred(   /* R.0:1.1:1.0:0.0:1.1:1.0:0 */
                                     0.2326530417870863);
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.0:1.1:1.0:1 */
                                     -1.9364772311558778);
                        }
                      }
                      if (defined_attr(1)) {  /* R.0:1.1:1.0:0.0:1.1:1.1 */
                        if (double_attr(1) <= 27.5) {
                          add_pred(   /* R.0:1.1:1.0:0.0:1.1:1.1:0 */
                                     -0.795665160482464);
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.0:1.1:1.1:1 */
                                     0.6957331345705193);
                        }
                      }
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:1.1:1.0:1 */
                         -1.0098463847227246);
            }
          }
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.1 */
    if (double_attr(2) <= 253.5) {
      add_pred(   /* R.1:0 */
                 -0.28193901812456557);
      if (defined_attr(2)) {  /* R.1:0.0 */
        if (double_attr(2) <= 77.5) {
          add_pred(   /* R.1:0.0:0 */
                     -5.6322140643484815);
        } else {
          add_pred(   /* R.1:0.0:1 */
                     -0.25466445936236226);
          if (defined_attr(1)) {  /* R.1:0.0:1.0 */
            if (double_attr(1) <= 21.5) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         -0.36998065008375536);
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         0.05241830661515938);
              if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0 */
                if (double_attr(2) <= 217.5) {
                  add_pred(   /* R.1:0.0:1.0:1.0:0 */
                             -0.13370551300102773);
                } else {
                  add_pred(   /* R.1:0.0:1.0:1.0:1 */
                             0.8130471026244881);
                }
              }
              if (defined_attr(2)) {  /* R.1:0.0:1.0:1.1 */
                if (double_attr(2) <= 160.5) {
                  add_pred(   /* R.1:0.0:1.0:1.1:0 */
                             -0.3497504919599209);
                  if (defined_attr(1)) {  /* R.1:0.0:1.0:1.1:0.0 */
                    if (double_attr(1) <= 50.5) {
                      add_pred(   /* R.1:0.0:1.0:1.1:0.0:0 */
                                 -0.5972729884746786);
                      if (defined_attr(2)) {  /* R.1:0.0:1.0:1.1:0.0:0.0 */
                        if (double_attr(2) <= 109.5) {
                          add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0 */
                                     -1.6886600358113621);
                          if (defined_attr(1)) {  /* R.1:0.0:1.0:1.1:0.0:0.0:0.0 */
                            if (double_attr(1) <= 46.5) {
                              add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:0 */
                                         -2.260287466710648);
                            } else {
                              add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:1 */
                                         -0.05363825445305385);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:1 */
                                     -0.12422769246228381);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:1.0:1.1:0.0:1 */
                                 0.22019374248864165);
                      if (defined_attr(0)) {  /* R.1:0.0:1.0:1.1:0.0:1.0 */
                        if (double_attr(0) <= 174.5) {
                          add_pred(   /* R.1:0.0:1.0:1.1:0.0:1.0:0 */
                                     0.2571770298582058);
                          if (defined_attr(0)) {  /* R.1:0.0:1.0:1.1:0.0:1.0:0.0 */
                            if (double_attr(0) <= 92.5) {
                              add_pred(   /* R.1:0.0:1.0:1.1:0.0:1.0:0.0:0 */
                                         -2.481907258956692);
                            } else {
                              add_pred(   /* R.1:0.0:1.0:1.1:0.0:1.0:0.0:1 */
                                         0.3170529958512137);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:0.0:1.0:1.1:0.0:1.0:1 */
                                     -1.784431711805463);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:1.0:1.1:1 */
                             0.22997613939525902);
                  if (defined_attr(0)) {  /* R.1:0.0:1.0:1.1:1.0 */
                    if (double_attr(0) <= 144.5) {
                      add_pred(   /* R.1:0.0:1.0:1.1:1.0:0 */
                                 0.06935381413829132);
                      if (defined_attr(0)) {  /* R.1:0.0:1.0:1.1:1.0:0.0 */
                        if (double_attr(0) <= 122.5) {
                          add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.0:0 */
                                     0.1330141741901973);
                        } else {
                          add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.0:1 */
                                     -0.9832776180251315);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:1.0:1.1:1.0:1 */
                                 2.162958210405414);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(0)) {  /* R.1:0.0:1.1 */
            if (double_attr(0) <= 115.5) {
              add_pred(   /* R.1:0.0:1.1:0 */
                         -0.17849585419057928);
            } else {
              add_pred(   /* R.1:0.0:1.1:1 */
                         0.1403327273856248);
              if (defined_attr(1)) {  /* R.1:0.0:1.1:1.0 */
                if (double_attr(1) <= 31.5) {
                  add_pred(   /* R.1:0.0:1.1:1.0:0 */
                             -0.10639309275996117);
                } else {
                  add_pred(   /* R.1:0.0:1.1:1.0:1 */
                             0.3191654968698546);
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 0.06604484558981379);
      if (defined_attr(0)) {  /* R.1:1.0 */
        if (double_attr(0) <= 123.5) {
          add_pred(   /* R.1:1.0:0 */
                     0.0987574674628451);
          if (defined_attr(2)) {  /* R.1:1.0:0.0 */
            if (double_attr(2) <= 254.5) {
              add_pred(   /* R.1:1.0:0.0:0 */
                         0.23463310366118723);
            } else {
              add_pred(   /* R.1:1.0:0.0:1 */
                         0.006239917051734893);
              if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0 */
                if (double_attr(1) <= 0.5) {
                  add_pred(   /* R.1:1.0:0.0:1.0:0 */
                             -2.234214457129362);
                } else {
                  add_pred(   /* R.1:1.0:0.0:1.0:1 */
                             0.010948179414978266);
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.1:1.0:0.1 */
            if (double_attr(1) <= 20.5) {
              add_pred(   /* R.1:1.0:0.1:0 */
                         0.04208910765520232);
            } else {
              add_pred(   /* R.1:1.0:0.1:1 */
                         0.8464519244724561);
            }
          }
        } else {
          add_pred(   /* R.1:1.0:1 */
                     -0.4247252940066466);
        }
      }
    }
  }
  return finalize_pred();
}
double predict_pool(void **attr, double *r) {
	int i, j, h, a;
	HashTableEntry_t *entry;
	char *s;
	static char **words = NULL;
	static int max_word_list_size = 0;
	int num_words;
	static char *buffer = NULL;
	static int buffer_size = 0;
	char **pat;
	Prediction_t p;
	if (!hash_table) {
		hash_table = (HashTableEntry_t **)
		malloc(hash_table_size * sizeof(HashTableEntry_t *));
		for (i = 0; i < hash_table_size; i++)
			hash_table[i] = NULL;
		for (i = 0; i < num_keys; i++) {
			h = hash(keys[i]);
			entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
			entry->key = keys[i];
			entry->id = i;
			entry->next = hash_table[h];
			hash_table[h] = entry;
		}
		for (i = 0; i < num_text_attr; i++)
			tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
	}
	for (i = 0; i < num_text_attr; i++) {
		a = text_attr[i];
		if (!defined_attr(a))
			continue;
		for (j = 0; j < num_keys; j++)
			tokens[a][j] = 0;
		while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size) {
			buffer_size = 2 * strlen((char*)attr[a]);
			buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
		}
		num_words = 0;
		for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
			if (num_words >= max_word_list_size) {
				max_word_list_size = 2 * max_word_list_size + 1;
				words = (char **) realloc(words, max_word_list_size * sizeof(char *));
			}
			words[num_words++] = s;
		}
		for (pat = text_patterns[i]; *pat; pat++) {
			set_pattern(num_words, words, *pat);
			while (more_tokens()) {
				s = next_token();
				for (entry = hash_table[hash(s)]; entry; entry = entry->next)
					if (!strcmp(entry->key, s)) {
						tokens[a][entry->id] = 1;
						break;
					}
			}
		}
	}
	reset_pred();
	add_pred(   /* R */
             -0.9706088386313558);
	if (defined_attr(0)) {  /* R.0 */
		if (double_attr(0) <= 105.5) {
			add_pred(   /* R.0:0 */
					 -1.2668189628606479);
			if (defined_attr(1)) {  /* R.0:0.0 */
				if (double_attr(1) <= 50.5) {
					add_pred(   /* R.0:0.0:0 */
							 -0.05721363967023377);
					if (defined_attr(2)) {  /* R.0:0.0:0.0 */
						if (double_attr(2) <= 138.5) {
							add_pred(   /* R.0:0.0:0.0:0 */
									 0.3181130653469017);
						} else {
							add_pred(   /* R.0:0.0:0.0:1 */
									 -1.1731714001520899);
						}
					}
					if (defined_attr(2)) {  /* R.0:0.0:0.1 */
						if (double_attr(2) <= 131.5) {
							add_pred(   /* R.0:0.0:0.1:0 */
									 0.2711451285822412);
							if (defined_attr(2)) {  /* R.0:0.0:0.1:0.0 */
								if (double_attr(2) <= 101.5) {
									add_pred(   /* R.0:0.0:0.1:0.0:0 */
											 -0.6517762526298023);
									if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:0.0 */
										if (double_attr(0) <= 74.5) {
											add_pred(   /* R.0:0.0:0.1:0.0:0.0:0 */
													 -0.6887338838462083);
										} else {
											add_pred(   /* R.0:0.0:0.1:0.0:0.0:1 */
													 0.7459179339749028);
											if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:0.0:1.0 */
												if (double_attr(1) <= 27.5) {
													add_pred(   /* R.0:0.0:0.1:0.0:0.0:1.0:0 */
															 0.7947911211382822);
												} else {
													add_pred(   /* R.0:0.0:0.1:0.0:0.0:1.0:1 */
															 -0.8491180554346106);
												}
											}
										}
									}
								} else {
									add_pred(   /* R.0:0.0:0.1:0.0:1 */
											 0.23570335421482164);
									if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0 */
										if (double_attr(0) <= 45.5) {
											add_pred(   /* R.0:0.0:0.1:0.0:1.0:0 */
													 0.2971858382293968);
											if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.0 */
												if (double_attr(0) <= 21.5) {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0 */
															 -0.1992319435030529);
													if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:0.0:0.0 */
														if (double_attr(1) <= 17.5) {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:0 */
																	 0.31572939595317956);
														} else {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1 */
																	 -0.42859087107979443);
															if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0 */
																if (double_attr(0) <= 15.5) {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0:0 */
																			 -1.3223099437301409);
																	if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0:0.0 */
																		if (double_attr(0) <= 10.5) {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0:0.0:0 */
																					 -2.60053943905002);
																		} else {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0:0.0:1 */
																					 -0.3949090753066721);
																		}
																	}
																} else {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:0.0:1.0:1 */
																			 0.0875490017921901);
																}
															}
														}
													}
												} else {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.0:1 */
															 0.3134412612988026);
												}
											}
											if (defined_attr(2)) {  /* R.0:0.0:0.1:0.0:1.0:0.1 */
												if (double_attr(2) <= 109.5) {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:0 */
															 -0.3466085897184138);
												} else {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1 */
															 0.17489031910799813);
													if (defined_attr(2)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0 */
														if (double_attr(2) <= 125.5) {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0 */
																	 0.2315981045119156);
															if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0 */
																if (double_attr(0) <= 30.5) {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0 */
																			 0.11303195766982765);
																	if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0 */
																		if (double_attr(1) <= 8.0) {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0:0 */
																					 0.37127562944370324);
																		} else {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0:1 */
																					 0.029528491590201312);
																			if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0:1.0 */
																				if (double_attr(0) <= 16.5) {
																					add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0:1.0:0 */
																							 -0.4554298303644331);
																				} else {
																					add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:0.0:1.0:1 */
																							 0.04510624911636559);
																				}
																			}
																		}
																	}
																} else {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:1 */
																			 -0.1963688321792747);
																	if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:1.0 */
																		if (double_attr(1) <= 19.5) {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:1.0:0 */
																					 0.010854971253413143);
																		} else {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:0.0:1.0:1 */
																					 -0.37612805772199664);
																		}
																	}
																}
															}
														} else {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1 */
																	 -0.24659150821087303);
															if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0 */
																if (double_attr(1) <= 26.5) {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0:0 */
																			 0.23812637305846612);
																} else {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0:1 */
																			 -0.3916780216697393);
																	if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0:1.0 */
																		if (double_attr(0) <= 18.5) {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0:1.0:0 */
																					 -1.5334817052096164);
																		} else {
																			add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.0:1.0:1 */
																					 -0.2671327721033523);
																		}
																	}
																}
															}
															if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.1 */
																if (double_attr(1) <= 30.5) {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.1:0 */
																			 0.043936811519015864);
																} else {
																	add_pred(   /* R.0:0.0:0.1:0.0:1.0:0.1:1.0:1.1:1 */
																			 -0.26227320183428177);
																}
															}
														}
													}
												}
											}
										} else {
											add_pred(   /* R.0:0.0:0.1:0.0:1.0:1 */
													 -0.2471428247948092);
											if (defined_attr(0)) {  /* R.0:0.0:0.1:0.0:1.0:1.0 */
												if (double_attr(0) <= 89.0) {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:0 */
															 -0.17481111104828767);
													if (defined_attr(2)) {  /* R.0:0.0:0.1:0.0:1.0:1.0:0.0 */
														if (double_attr(2) <= 121.5) {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:0.0:0 */
																	 -0.37979110135295485);
														} else {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:0.0:1 */
																	 0.2321607600049857);
														}
													}
													if (defined_attr(1)) {  /* R.0:0.0:0.1:0.0:1.0:1.0:0.1 */
														if (double_attr(1) <= 23.5) {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:0.1:0 */
																	 -0.006662797741938771);
														} else {
															add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:0.1:1 */
																	 -2.422393839492332);
														}
													}
												} else {
													add_pred(   /* R.0:0.0:0.1:0.0:1.0:1.0:1 */
															 0.16191756528014026);
												}
											}
										}
									}
								}
							}
						} else {
							add_pred(   /* R.0:0.0:0.1:1 */
									 -0.4259084094134339);
							if (defined_attr(2)) {  /* R.0:0.0:0.1:1.0 */
								if (double_attr(2) <= 164.5) {
									add_pred(   /* R.0:0.0:0.1:1.0:0 */
											 -0.1532325487380561);
								} else {
									add_pred(   /* R.0:0.0:0.1:1.0:1 */
											 -3.531059779805757);
								}
							}
							if (defined_attr(2)) {  /* R.0:0.0:0.1:1.1 */
								if (double_attr(2) <= 145.5) {
									add_pred(   /* R.0:0.0:0.1:1.1:0 */
											 0.19063765964323726);
									if (defined_attr(1)) {  /* R.0:0.0:0.1:1.1:0.0 */
										if (double_attr(1) <= 23.5) {
											add_pred(   /* R.0:0.0:0.1:1.1:0.0:0 */
													 0.3319226205112556);
											if (defined_attr(0)) {  /* R.0:0.0:0.1:1.1:0.0:0.0 */
												if (double_attr(0) <= 43.0) {
													add_pred(   /* R.0:0.0:0.1:1.1:0.0:0.0:0 */
															 0.40133348202634656);
													if (defined_attr(0)) {  /* R.0:0.0:0.1:1.1:0.0:0.0:0.0 */
														if (double_attr(0) <= 31.5) {
															add_pred(   /* R.0:0.0:0.1:1.1:0.0:0.0:0.0:0 */
																	 0.0576999768355745);
														} else {
															add_pred(   /* R.0:0.0:0.1:1.1:0.0:0.0:0.0:1 */
																	 0.5171731421199098);
														}
													}
												} else {
													add_pred(   /* R.0:0.0:0.1:1.1:0.0:0.0:1 */
															 -0.02696876730794192);
												}
											}
										} else {
											add_pred(   /* R.0:0.0:0.1:1.1:0.0:1 */
													 -0.03210467099728817);
											if (defined_attr(2)) {  /* R.0:0.0:0.1:1.1:0.0:1.0 */
												if (double_attr(2) <= 138.5) {
													add_pred(   /* R.0:0.0:0.1:1.1:0.0:1.0:0 */
															 -0.11978239565246868);
												} else {
													add_pred(   /* R.0:0.0:0.1:1.1:0.0:1.0:1 */
															 0.3331866529208258);
													if (defined_attr(0)) {  /* R.0:0.0:0.1:1.1:0.0:1.0:1.0 */
														if (double_attr(0) <= 19.5) {
															add_pred(   /* R.0:0.0:0.1:1.1:0.0:1.0:1.0:0 */
																	 -1.9463490372441035);
														} else {
															add_pred(   /* R.0:0.0:0.1:1.1:0.0:1.0:1.0:1 */
																	 0.25994501724868224);
														}
													}
												}
											}
										}
									}
								} else {
									add_pred(   /* R.0:0.0:0.1:1.1:1 */
											 -0.3246246874952712);
								}
							}
						}
					}
				} else {
					add_pred(   /* R.0:0.0:1 */
							 -1.058887654821413);
					if (defined_attr(0)) {  /* R.0:0.0:1.0 */
						if (double_attr(0) <= 26.5) {
							add_pred(   /* R.0:0.0:1.0:0 */
									 -1.1803607436061982);
							if (defined_attr(1)) {  /* R.0:0.0:1.0:0.0 */
								if (double_attr(1) <= 70.5) {
									add_pred(   /* R.0:0.0:1.0:0.0:0 */
											 9.085638832835888E-4);
									if (defined_attr(0)) {  /* R.0:0.0:1.0:0.0:0.0 */
										if (double_attr(0) <= 19.5) {
											add_pred(   /* R.0:0.0:1.0:0.0:0.0:0 */
													 -1.4902604522691503);
										} else {
											add_pred(   /* R.0:0.0:1.0:0.0:0.0:1 */
													 0.9134149085965761);
											if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0:0.0:1.0 */
												if (double_attr(2) <= 129.5) {
													add_pred(   /* R.0:0.0:1.0:0.0:0.0:1.0:0 */
															 0.660264280416128);
												} else {
													add_pred(   /* R.0:0.0:1.0:0.0:0.0:1.0:1 */
															 -0.35812958652981564);
												}
											}
										}
									}
									if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0:0.1 */
										if (double_attr(2) <= 140.5) {
											add_pred(   /* R.0:0.0:1.0:0.0:0.1:0 */
													 0.7523353888284319);
										} else {
											add_pred(   /* R.0:0.0:1.0:0.0:0.1:1 */
													 -2.6676129272395435);
										}
									}
								} else {
									add_pred(   /* R.0:0.0:1.0:0.0:1 */
											 -4.033864884711816);
								}
							}
						} else {
							add_pred(   /* R.0:0.0:1.0:1 */
									 0.6971544576909855);
							if (defined_attr(2)) {  /* R.0:0.0:1.0:1.0 */
								if (double_attr(2) <= 147.5) {
									add_pred(   /* R.0:0.0:1.0:1.0:0 */
											 -1.0801200642734483);
								} else {
									add_pred(   /* R.0:0.0:1.0:1.0:1 */
											 2.741376840911479);
									if (defined_attr(1)) {  /* R.0:0.0:1.0:1.0:1.0 */
										if (double_attr(1) <= 68.0) {
											add_pred(   /* R.0:0.0:1.0:1.0:1.0:0 */
													 -2.4159180204195776);
										} else {
											add_pred(   /* R.0:0.0:1.0:1.0:1.0:1 */
													 2.3383805148563717);
											if (defined_attr(0)) {  /* R.0:0.0:1.0:1.0:1.0:1.0 */
												if (double_attr(0) <= 63.5) {
													add_pred(   /* R.0:0.0:1.0:1.0:1.0:1.0:0 */
															 -1.9705875470035115);
												} else {
													add_pred(   /* R.0:0.0:1.0:1.0:1.0:1.0:1 */
															 3.2105427478343587);
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		} else {
			add_pred(   /* R.0:1 */
					 1.2471807524938336);
			if (defined_attr(1)) {  /* R.0:1.0 */
				if (double_attr(1) <= 84.5) {
					add_pred(   /* R.0:1.0:0 */
							 -0.4819419683566663);
					if (defined_attr(1)) {  /* R.0:1.0:0.0 */
						if (double_attr(1) <= 48.5) {
							add_pred(   /* R.0:1.0:0.0:0 */
									 -0.2673261961779825);
							if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0 */
								if (double_attr(2) <= 172.5) {
									add_pred(   /* R.0:1.0:0.0:0.0:0 */
											 -0.025926124207263725);
								} else {
									add_pred(   /* R.0:1.0:0.0:0.0:1 */
											 -2.8932487205230024);
								}
							}
						} else {
							add_pred(   /* R.0:1.0:0.0:1 */
									 0.5546871274084343);
							if (defined_attr(2)) {  /* R.0:1.0:0.0:1.0 */
								if (double_attr(2) <= 129.5) {
									add_pred(   /* R.0:1.0:0.0:1.0:0 */
											 -0.4954136344631851);
								} else {
									add_pred(   /* R.0:1.0:0.0:1.0:1 */
											 0.9577778512595095);
									if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0:1.0 */
										if (double_attr(1) <= 58.5) {
											add_pred(   /* R.0:1.0:0.0:1.0:1.0:0 */
													 -0.055116622449246484);
										} else {
											add_pred(   /* R.0:1.0:0.0:1.0:1.0:1 */
													 2.558142860950654);
										}
									}
								}
							}
							if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1 */
								if (double_attr(2) <= 117.5) {
									add_pred(   /* R.0:1.0:0.0:1.1:0 */
											 -1.5076559026090324);
								} else {
									add_pred(   /* R.0:1.0:0.0:1.1:1 */
											 0.17353240820049462);
								}
							}
						}
					}
					if (defined_attr(1)) {  /* R.0:1.0:0.1 */
						if (double_attr(1) <= 16.5) {
							add_pred(   /* R.0:1.0:0.1:0 */
									 -0.43586008978034246);
							if (defined_attr(0)) {  /* R.0:1.0:0.1:0.0 */
								if (double_attr(0) <= 117.0) {
									add_pred(   /* R.0:1.0:0.1:0.0:0 */
											 -0.3900539154283348);
								} else {
									add_pred(   /* R.0:1.0:0.1:0.0:1 */
											 0.007932814501172343);
									if (defined_attr(2)) {  /* R.0:1.0:0.1:0.0:1.0 */
										if (double_attr(2) <= 114.5) {
											add_pred(   /* R.0:1.0:0.1:0.0:1.0:0 */
													 -0.47213522451217754);
										} else {
											add_pred(   /* R.0:1.0:0.1:0.0:1.0:1 */
													 0.23855386992242258);
											if (defined_attr(0)) {  /* R.0:1.0:0.1:0.0:1.0:1.0 */
												if (double_attr(0) <= 167.5) {
													add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:0 */
															 0.35573240973705766);
													if (defined_attr(1)) {  /* R.0:1.0:0.1:0.0:1.0:1.0:0.0 */
														if (double_attr(1) <= 13.5) {
															add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:0.0:0 */
																	 0.03846652393530336);
														} else {
															add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:0.0:1 */
																	 1.5639554785607959);
														}
													}
												} else {
													add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:1 */
															 -0.7272106837624976);
													if (defined_attr(2)) {  /* R.0:1.0:0.1:0.0:1.0:1.0:1.0 */
														if (double_attr(2) <= 127.5) {
															add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:1.0:0 */
																	 0.07015634839280212);
														} else {
															add_pred(   /* R.0:1.0:0.1:0.0:1.0:1.0:1.0:1 */
																	 -2.4048200730758946);
														}
													}
												}
											}
										}
									}
								}
							}
						} else {
							add_pred(   /* R.0:1.0:0.1:1 */
									 0.03518398694284202);
							if (defined_attr(0)) {  /* R.0:1.0:0.1:1.0 */
								if (double_attr(0) <= 111.5) {
									add_pred(   /* R.0:1.0:0.1:1.0:0 */
											 -0.06280561487052701);
								} else {
									add_pred(   /* R.0:1.0:0.1:1.0:1 */
											 0.5611015569473436);
									if (defined_attr(0)) {  /* R.0:1.0:0.1:1.0:1.0 */
										if (double_attr(0) <= 173.5) {
											add_pred(   /* R.0:1.0:0.1:1.0:1.0:0 */
													 0.44565626722802854);
											if (defined_attr(0)) {  /* R.0:1.0:0.1:1.0:1.0:0.0 */
												if (double_attr(0) <= 129.5) {
													add_pred(   /* R.0:1.0:0.1:1.0:1.0:0.0:0 */
															 0.011858587832771411);
												} else {
													add_pred(   /* R.0:1.0:0.1:1.0:1.0:0.0:1 */
															 1.90687888811679);
												}
											}
										} else {
											add_pred(   /* R.0:1.0:0.1:1.0:1.0:1 */
													 -1.644289118917659);
										}
									}
								}
							}
							if (defined_attr(2)) {  /* R.0:1.0:0.1:1.1 */
								if (double_attr(2) <= 129.5) {
									add_pred(   /* R.0:1.0:0.1:1.1:0 */
											 0.15555203198936043);
								} else {
									add_pred(   /* R.0:1.0:0.1:1.1:1 */
											 -0.18709646518860995);
									if (defined_attr(1)) {  /* R.0:1.0:0.1:1.1:1.0 */
										if (double_attr(1) <= 35.5) {
											add_pred(   /* R.0:1.0:0.1:1.1:1.0:0 */
													 -0.3492735439911627);
											if (defined_attr(0)) {  /* R.0:1.0:0.1:1.1:1.0:0.0 */
												if (double_attr(0) <= 116.0) {
													add_pred(   /* R.0:1.0:0.1:1.1:1.0:0.0:0 */
															 -0.26298224869153475);
													if (defined_attr(2)) {  /* R.0:1.0:0.1:1.1:1.0:0.0:0.0 */
														if (double_attr(2) <= 141.5) {
															add_pred(   /* R.0:1.0:0.1:1.1:1.0:0.0:0.0:0 */
																	 0.0021198485566544314);
														} else {
															add_pred(   /* R.0:1.0:0.1:1.1:1.0:0.0:0.0:1 */
																	 -0.7227494986406207);
														}
													}
												} else {
													add_pred(   /* R.0:1.0:0.1:1.1:1.0:0.0:1 */
															 1.9742862788996483);
												}
											}
										} else {
											add_pred(   /* R.0:1.0:0.1:1.1:1.0:1 */
													 0.12216646183888558);
											if (defined_attr(2)) {  /* R.0:1.0:0.1:1.1:1.0:1.0 */
												if (double_attr(2) <= 147.5) {
													add_pred(   /* R.0:1.0:0.1:1.1:1.0:1.0:0 */
															 -0.12236681166720359);
												} else {
													add_pred(   /* R.0:1.0:0.1:1.1:1.0:1.0:1 */
															 0.5607065027487999);
												}
											}
										}
									}
								}
							}
						}
					}
				} else {
					add_pred(   /* R.0:1.0:1 */
							 2.557152985331817);
					if (defined_attr(2)) {  /* R.0:1.0:1.0 */
						if (double_attr(2) <= 103.5) {
							add_pred(   /* R.0:1.0:1.0:0 */
									 -3.069309705786398);
						} else {
							add_pred(   /* R.0:1.0:1.0:1 */
									 3.940048348164969);
						}
					}
				}
			}
		}
	}
	if (defined_attr(0)) {  /* R.1 */
		if (double_attr(0) <= 107.5) {
			add_pred(   /* R.1:0 */
					 -0.6144932277533135);
			if (defined_attr(0)) {  /* R.1:0.0 */
				if (double_attr(0) <= 34.5) {
					add_pred(   /* R.1:0.0:0 */
							 0.10626047451816698);
					if (defined_attr(0)) {  /* R.1:0.0:0.0 */
						if (double_attr(0) <= 22.5) {
							add_pred(   /* R.1:0.0:0.0:0 */
									 -0.2041703438574149);
							if (defined_attr(2)) {  /* R.1:0.0:0.0:0.0 */
								if (double_attr(2) <= 128.5) {
									add_pred(   /* R.1:0.0:0.0:0.0:0 */
											 0.03603509325654787);
								} else {
									add_pred(   /* R.1:0.0:0.0:0.0:1 */
											 -0.7808503369355065);
									if (defined_attr(2)) {  /* R.1:0.0:0.0:0.0:1.0 */
										if (double_attr(2) <= 147.5) {
											add_pred(   /* R.1:0.0:0.0:0.0:1.0:0 */
													 -0.3624489313148012);
										} else {
											add_pred(   /* R.1:0.0:0.0:0.0:1.0:1 */
													 -2.6652712916006283);
										}
									}
									if (defined_attr(0)) {  /* R.1:0.0:0.0:0.0:1.1 */
										if (double_attr(0) <= 18.5) {
											add_pred(   /* R.1:0.0:0.0:0.0:1.1:0 */
													 -0.8401220715962276);
										} else {
											add_pred(   /* R.1:0.0:0.0:0.0:1.1:1 */
													 0.012522935820506176);
										}
									}
								}
							}
						} else {
							add_pred(   /* R.1:0.0:0.0:1 */
									 0.24064655691504774);
							if (defined_attr(1)) {  /* R.1:0.0:0.0:1.0 */
								if (double_attr(1) <= 41.5) {
									add_pred(   /* R.1:0.0:0.0:1.0:0 */
											 -0.003981098121508221);
									if (defined_attr(1)) {  /* R.1:0.0:0.0:1.0:0.0 */
										if (double_attr(1) <= 20.5) {
											add_pred(   /* R.1:0.0:0.0:1.0:0.0:0 */
													 0.17302525187841855);
										} else {
											add_pred(   /* R.1:0.0:0.0:1.0:0.0:1 */
													 -0.07236919260769388);
										}
									}
								} else {
									add_pred(   /* R.1:0.0:0.0:1.0:1 */
											 0.26499188596740775);
									if (defined_attr(0)) {  /* R.1:0.0:0.0:1.0:1.0 */
										if (double_attr(0) <= 25.5) {
											add_pred(   /* R.1:0.0:0.0:1.0:1.0:0 */
													 0.028234497904375593);
										} else {
											add_pred(   /* R.1:0.0:0.0:1.0:1.0:1 */
													 0.4412818133616111);
											if (defined_attr(1)) {  /* R.1:0.0:0.0:1.0:1.0:1.0 */
												if (double_attr(1) <= 62.5) {
													add_pred(   /* R.1:0.0:0.0:1.0:1.0:1.0:0 */
															 0.3198555146840395);
												} else {
													add_pred(   /* R.1:0.0:0.0:1.0:1.0:1.0:1 */
															 -2.2117132706376115);
												}
											}
										}
									}
								}
							}
						}
					}
					if (defined_attr(2)) {  /* R.1:0.0:0.1 */
						if (double_attr(2) <= 111.5) {
							add_pred(   /* R.1:0.0:0.1:0 */
									 -0.12692531819990044);
							if (defined_attr(1)) {  /* R.1:0.0:0.1:0.0 */
								if (double_attr(1) <= 47.5) {
									add_pred(   /* R.1:0.0:0.1:0.0:0 */
											 -0.15244315500758882);
									if (defined_attr(2)) {  /* R.1:0.0:0.1:0.0:0.0 */
										if (double_attr(2) <= 105.5) {
											add_pred(   /* R.1:0.0:0.1:0.0:0.0:0 */
													 -0.25740133970210616);
										} else {
											add_pred(   /* R.1:0.0:0.1:0.0:0.0:1 */
													 0.010516064640428967);
										}
									}
								} else {
									add_pred(   /* R.1:0.0:0.1:0.0:1 */
											 0.3619560303887277);
								}
							}
						} else {
							add_pred(   /* R.1:0.0:0.1:1 */
									 0.15337905063527052);
							if (defined_attr(1)) {  /* R.1:0.0:0.1:1.0 */
								if (double_attr(1) <= 64.5) {
									add_pred(   /* R.1:0.0:0.1:1.0:0 */
											 0.08407839402736028);
								} else {
									add_pred(   /* R.1:0.0:0.1:1.0:1 */
											 -2.7780012812332484);
								}
							}
						}
					}
				} else {
					add_pred(   /* R.1:0.0:1 */
							 -0.18075724171835966);
					if (defined_attr(1)) {  /* R.1:0.0:1.0 */
						if (double_attr(1) <= 21.5) {
							add_pred(   /* R.1:0.0:1.0:0 */
									 0.059692828050422295);
							if (defined_attr(2)) {  /* R.1:0.0:1.0:0.0 */
								if (double_attr(2) <= 107.5) {
									add_pred(   /* R.1:0.0:1.0:0.0:0 */
											 0.3476562998197357);
									if (defined_attr(0)) {  /* R.1:0.0:1.0:0.0:0.0 */
										if (double_attr(0) <= 81.0) {
											add_pred(   /* R.1:0.0:1.0:0.0:0.0:0 */
													 -0.2802093531361031);
										} else {
											add_pred(   /* R.1:0.0:1.0:0.0:0.0:1 */
													 0.34858640962931897);
											if (defined_attr(1)) {  /* R.1:0.0:1.0:0.0:0.0:1.0 */
												if (double_attr(1) <= 9.5) {
													add_pred(   /* R.1:0.0:1.0:0.0:0.0:1.0:0 */
															 -0.3714374076096362);
												} else {
													add_pred(   /* R.1:0.0:1.0:0.0:0.0:1.0:1 */
															 0.4611730411174567);
												}
											}
										}
									}
								} else {
									add_pred(   /* R.1:0.0:1.0:0.0:1 */
											 -0.010033011187407282);
									if (defined_attr(1)) {  /* R.1:0.0:1.0:0.0:1.0 */
										if (double_attr(1) <= 11.5) {
											add_pred(   /* R.1:0.0:1.0:0.0:1.0:0 */
													 0.1143352333236602);
										} else {
											add_pred(   /* R.1:0.0:1.0:0.0:1.0:1 */
													 -0.1357763210944825);
										}
									}
								}
							}
						} else {
							add_pred(   /* R.1:0.0:1.0:1 */
									 -0.26813807808931706);
							if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0 */
								if (double_attr(0) <= 101.5) {
									add_pred(   /* R.1:0.0:1.0:1.0:0 */
											 -0.6317520161893745);
									if (defined_attr(1)) {  /* R.1:0.0:1.0:1.0:0.0 */
										if (double_attr(1) <= 31.5) {
											add_pred(   /* R.1:0.0:1.0:1.0:0.0:0 */
													 -0.09104805461189638);
										} else {
											add_pred(   /* R.1:0.0:1.0:1.0:0.0:1 */
													 -0.8812015938861241);
											if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0:0.0:1.0 */
												if (double_attr(2) <= 125.5) {
													add_pred(   /* R.1:0.0:1.0:1.0:0.0:1.0:0 */
															 0.12419792407837325);
												} else {
													add_pred(   /* R.1:0.0:1.0:1.0:0.0:1.0:1 */
															 -0.998099167290871);
												}
											}
										}
									}
									if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0:0.1 */
										if (double_attr(0) <= 36.5) {
											add_pred(   /* R.1:0.0:1.0:1.0:0.1:0 */
													 0.4580994467265234);
										} else {
											add_pred(   /* R.1:0.0:1.0:1.0:0.1:1 */
													 -0.14840726502270385);
											if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0:0.1:1.0 */
												if (double_attr(2) <= 127.5) {
													add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:0 */
															 0.18381015100270995);
													if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0:0.1:1.0:0.0 */
														if (double_attr(0) <= 83.5) {
															add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:0.0:0 */
																	 -0.7079908023363208);
														} else {
															add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:0.0:1 */
																	 0.36643640823593193);
														}
													}
												} else {
													add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:1 */
															 -0.5195850888597024);
													if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0:0.1:1.0:1.0 */
														if (double_attr(0) <= 97.5) {
															add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:1.0:0 */
																	 -0.8694935250855456);
														} else {
															add_pred(   /* R.1:0.0:1.0:1.0:0.1:1.0:1.0:1 */
																	 0.1262216257681964);
														}
													}
												}
											}
										}
									}
								} else {
									add_pred(   /* R.1:0.0:1.0:1.0:1 */
											 0.18504271369726372);
									if (defined_attr(1)) {  /* R.1:0.0:1.0:1.0:1.0 */
										if (double_attr(1) <= 43.5) {
											add_pred(   /* R.1:0.0:1.0:1.0:1.0:0 */
													 0.23307897343616102);
											if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0:1.0:0.0 */
												if (double_attr(2) <= 126.5) {
													add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:0 */
															 0.5673337008292683);
												} else {
													add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:1 */
															 -0.09610184935267346);
												}
											}
										} else {
											add_pred(   /* R.1:0.0:1.0:1.0:1.0:1 */
													 -0.33318636695124215);
											if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0:1.0:1.0 */
												if (double_attr(2) <= 149.5) {
													add_pred(   /* R.1:0.0:1.0:1.0:1.0:1.0:0 */
															 -0.35284022627965705);
												} else {
													add_pred(   /* R.1:0.0:1.0:1.0:1.0:1.0:1 */
															 1.5289677432437314);
												}
											}
										}
									}
									if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0:1.1 */
										if (double_attr(0) <= 103.5) {
											add_pred(   /* R.1:0.0:1.0:1.0:1.1:0 */
													 -0.2919471708100529);
											if (defined_attr(1)) {  /* R.1:0.0:1.0:1.0:1.1:0.0 */
												if (double_attr(1) <= 28.5) {
													add_pred(   /* R.1:0.0:1.0:1.0:1.1:0.0:0 */
															 0.2687432086800946);
												} else {
													add_pred(   /* R.1:0.0:1.0:1.0:1.1:0.0:1 */
															 -0.37043667962283783);
												}
											}
										} else {
											add_pred(   /* R.1:0.0:1.0:1.0:1.1:1 */
													 0.2134052236820584);
										}
									}
								}
							}
							if (defined_attr(2)) {  /* R.1:0.0:1.0:1.1 */
								if (double_attr(2) <= 98.5) {
									add_pred(   /* R.1:0.0:1.0:1.1:0 */
											 -1.465641346233567);
								} else {
									add_pred(   /* R.1:0.0:1.0:1.1:1 */
											 0.07338876245700598);
								}
							}
						}
					}
				}
			}
		} else {
			add_pred(   /* R.1:1 */
					 0.9006864254996889);
			if (defined_attr(1)) {  /* R.1:1.0 */
				if (double_attr(1) <= 20.5) {
					add_pred(   /* R.1:1.0:0 */
							 -1.120881132143901);
				} else {
					add_pred(   /* R.1:1.0:1 */
							 0.5957125553753494);
					if (defined_attr(0)) {  /* R.1:1.0:1.0 */
						if (double_attr(0) <= 109.5) {
							add_pred(   /* R.1:1.0:1.0:0 */
									 -0.3054428869873427);
						} else {
							add_pred(   /* R.1:1.0:1.0:1 */
									 0.505539034016328);
							if (defined_attr(1)) {  /* R.1:1.0:1.0:1.0 */
								if (double_attr(1) <= 24.5) {
									add_pred(   /* R.1:1.0:1.0:1.0:0 */
											 -0.5020494295474099);
								} else {
									add_pred(   /* R.1:1.0:1.0:1.0:1 */
											 0.2860990060169454);
								}
							}
						}
					}
				}
			}
			if (defined_attr(2)) {  /* R.1:1.1 */
				if (double_attr(2) <= 107.5) {
					add_pred(   /* R.1:1.1:0 */
							 -1.7457633518069728);
					if (defined_attr(0)) {  /* R.1:1.1:0.0 */
						if (double_attr(0) <= 149.0) {
							add_pred(   /* R.1:1.1:0.0:0 */
									 -0.09306758119280821);
						} else {
							add_pred(   /* R.1:1.1:0.0:1 */
									 -2.9328523167086376);
						}
					}
				} else {
					add_pred(   /* R.1:1.1:1 */
							 0.0033863033823171252);
					if (defined_attr(0)) {  /* R.1:1.1:1.0 */
						if (double_attr(0) <= 108.5) {
							add_pred(   /* R.1:1.1:1.0:0 */
									 -0.2909940393995728);
						} else {
							add_pred(   /* R.1:1.1:1.0:1 */
									 0.053433662945654575);
							if (defined_attr(1)) {  /* R.1:1.1:1.0:1.0 */
								if (double_attr(1) <= 44.5) {
									add_pred(   /* R.1:1.1:1.0:1.0:0 */
											 -0.028758502595755176);
								} else {
									add_pred(   /* R.1:1.1:1.0:1.0:1 */
											 0.6715917140278849);
								}
							}
						}
					}
				}
			}
		}
	}
	if (defined_attr(2)) {  /* R.2 */
		if (double_attr(2) <= 90.5) {
			add_pred(   /* R.2:0 */
					 -1.2968929026154028);
		} else {
			add_pred(   /* R.2:1 */
					 0.03935756229889062);
		}
	}
	return finalize_pred();
}
