/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:
  double predict(void **attr, double *ret)
The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.
Specifically, these pointers are:
     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V
The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).
These scores correspond to the classes as follows:
            index       class name
           ------------------------
               0        non-buoy
               1        buoy
This classifier was automatically generated by jboost on
Tue Dec 08 00:11:16 GMT-00:08 2009.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <values.h>
#include "strlcpy.h"
typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))
#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};
static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;
static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}
#define more_tokens()  (cur_word <= num_words - pattern_len)
#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}
static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;
  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);
  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}
static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;
  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }
  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= MAXINT - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}
double predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;
  Prediction_t p;
  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }
  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;
    while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen((char*)attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }
  reset_pred();
  add_pred(   /* R */
             0.2895938885913509);
  if (defined_attr(0)) {  /* R.0 */
    if (double_attr(0) <= 0.2093253968253968) {
      add_pred(   /* R.0:0 */
                 2.1070740461131403);
      if (defined_attr(2)) {  /* R.0:0.0 */
        if (double_attr(2) <= 0.9509803950786591) {
          add_pred(   /* R.0:0.0:0 */
                     -0.5534405661355293);
          if (defined_attr(0)) {  /* R.0:0.0:0.0 */
            if (double_attr(0) <= 0.14087301587301587) {
              add_pred(   /* R.0:0.0:0.0:0 */
                         0.05122369872409009);
              if (defined_attr(1)) {  /* R.0:0.0:0.0:0.0 */
                if (double_attr(1) <= 0.023715785526809148) {
                  add_pred(   /* R.0:0.0:0.0:0.0:0 */
                             -0.5238411952354982);
                  if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0:0.0 */
                    if (double_attr(2) <= 0.5176470875740051) {
                      add_pred(   /* R.0:0.0:0.0:0.0:0.0:0 */
                                 -0.15150502425132614);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.0:0.0:1 */
                                 -1.843731617578838);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:0.0:0.0:1 */
                             0.13649630081608669);
                }
              }
            } else {
              add_pred(   /* R.0:0.0:0.0:1 */
                         -0.40751510409957115);
              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0 */
                if (double_attr(1) <= 0.06405128205128205) {
                  add_pred(   /* R.0:0.0:0.0:1.0:0 */
                             -0.003673988193642938);
                } else {
                  add_pred(   /* R.0:0.0:0.0:1.0:1 */
                             -2.447509189502602);
                }
              }
              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.1 */
                if (double_attr(1) <= 0.04115296030348191) {
                  add_pred(   /* R.0:0.0:0.0:1.1:0 */
                             0.25894730441572267);
                } else {
                  add_pred(   /* R.0:0.0:0.0:1.1:1 */
                             -0.43727633190180853);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.0:1 */
                     0.7102924836239466);
          if (defined_attr(1)) {  /* R.0:0.0:1.0 */
            if (double_attr(1) <= 0.07465647676393392) {
              add_pred(   /* R.0:0.0:1.0:0 */
                         -0.15977053276944583);
              if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0 */
                if (double_attr(2) <= 0.9862745106220245) {
                  add_pred(   /* R.0:0.0:1.0:0.0:0 */
                             -1.3845213355068189);
                } else {
                  add_pred(   /* R.0:0.0:1.0:0.0:1 */
                             0.029606149004318363);
                }
              }
            } else {
              add_pred(   /* R.0:0.0:1.0:1 */
                         3.188915426030187);
            }
          }
          if (defined_attr(1)) {  /* R.0:0.0:1.1 */
            if (double_attr(1) <= 0.05893932376100046) {
              add_pred(   /* R.0:0.0:1.1:0 */
                         -0.15388418261452122);
            } else {
              add_pred(   /* R.0:0.0:1.1:1 */
                         0.8014894176064699);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 -1.0850786181141103);
      if (defined_attr(1)) {  /* R.0:1.0 */
        if (double_attr(1) <= 0.30449179383818026) {
          add_pred(   /* R.0:1.0:0 */
                     -0.20021274320227567);
        } else {
          add_pred(   /* R.0:1.0:1 */
                     -5.278373661621676);
        }
      }
      if (defined_attr(1)) {  /* R.0:1.1 */
        if (double_attr(1) <= 0.12982056111827103) {
          add_pred(   /* R.0:1.1:0 */
                     0.6284918805458667);
          if (defined_attr(2)) {  /* R.0:1.1:0.0 */
            if (double_attr(2) <= 0.39411765336990356) {
              add_pred(   /* R.0:1.1:0.0:0 */
                         -2.002454596608117);
            } else {
              add_pred(   /* R.0:1.1:0.0:1 */
                         0.16946484593687527);
              if (defined_attr(1)) {  /* R.0:1.1:0.0:1.0 */
                if (double_attr(1) <= 0.02748695808598669) {
                  add_pred(   /* R.0:1.1:0.0:1.0:0 */
                             0.3977923294491158);
                  if (defined_attr(2)) {  /* R.0:1.1:0.0:1.0:0.0 */
                    if (double_attr(2) <= 0.42941176891326904) {
                      add_pred(   /* R.0:1.1:0.0:1.0:0.0:0 */
                                 -0.9929561589307663);
                    } else {
                      add_pred(   /* R.0:1.1:0.0:1.0:0.0:1 */
                                 0.3194755992645927);
                    }
                  }
                  if (defined_attr(1)) {  /* R.0:1.1:0.0:1.0:0.1 */
                    if (double_attr(1) <= 0.023166368515205725) {
                      add_pred(   /* R.0:1.1:0.0:1.0:0.1:0 */
                                 -0.02780299720082037);
                    } else {
                      add_pred(   /* R.0:1.1:0.0:1.0:0.1:1 */
                                 0.44895239026331846);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:0.0:1.0:1 */
                             -0.006056077411462982);
                  if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0 */
                    if (double_attr(0) <= 0.5937001594896332) {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:0 */
                                 0.011409175226425297);
                    } else {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:1 */
                                 -0.37907100941341304);
                      if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.8090277777777778) {
                          add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0 */
                                     -0.4760647604652937);
                          if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0:1.0:0.0 */
                            if (double_attr(0) <= 0.6361111111111111) {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:0 */
                                         0.04004821443958524);
                            } else {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:1 */
                                         -0.8911628361582519);
                              if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 0.6933760683760685) {
                                  add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:1.0:0 */
                                             -1.9867200200450612);
                                } else {
                                  add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:0.0:1.0:1 */
                                             0.12096561283244926);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1 */
                                     1.0913621802028517);
                          if (defined_attr(2)) {  /* R.0:1.1:0.0:1.0:1.0:1.0:1.0 */
                            if (double_attr(2) <= 0.5117647349834442) {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1.0:0 */
                                         0.016207840479305045);
                            } else {
                              add_pred(   /* R.0:1.1:0.0:1.0:1.0:1.0:1.0:1 */
                                         1.9326773992110406);
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.1:1 */
                     -0.5248897024186456);
          if (defined_attr(0)) {  /* R.0:1.1:1.0 */
            if (double_attr(0) <= 0.7022727272727273) {
              add_pred(   /* R.0:1.1:1.0:0 */
                         -0.34537967906160166);
              if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0 */
                if (double_attr(0) <= 0.5596764346764347) {
                  add_pred(   /* R.0:1.1:1.0:0.0:0 */
                             0.09635137572546854);
                  if (defined_attr(0)) {  /* R.0:1.1:1.0:0.0:0.0 */
                    if (double_attr(0) <= 0.481612685560054) {
                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:0 */
                                 -1.8815644625619146);
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.0:0.0:1 */
                                 0.10045905569247501);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:1.0:0.0:1 */
                             -1.7061903290276594);
                }
              }
              if (defined_attr(1)) {  /* R.0:1.1:1.0:0.1 */
                if (double_attr(1) <= 0.1971316952811761) {
                  add_pred(   /* R.0:1.1:1.0:0.1:0 */
                             0.1688102117517486);
                  if (defined_attr(2)) {  /* R.0:1.1:1.0:0.1:0.0 */
                    if (double_attr(2) <= 0.5117647349834442) {
                      add_pred(   /* R.0:1.1:1.0:0.1:0.0:0 */
                                 0.042573157820427546);
                      if (defined_attr(1)) {  /* R.0:1.1:1.0:0.1:0.0:0.0 */
                        if (double_attr(1) <= 0.14438717067583046) {
                          add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:0 */
                                     0.40296476484825633);
                          if (defined_attr(2)) {  /* R.0:1.1:1.0:0.1:0.0:0.0:0.0 */
                            if (double_attr(2) <= 0.37843137979507446) {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:0.0:0 */
                                         -1.2532245452762494);
                            } else {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:0.0:1 */
                                         0.14811135404170242);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:1 */
                                     -0.07676797773609068);
                          if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:0.0:0.0:1.0 */
                            if (double_attr(0) <= 0.490625) {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:1.0:0 */
                                         -1.223368862921601);
                            } else {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:0.0:1.0:1 */
                                         -0.05751690083096648);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.1:0.0:1 */
                                 0.5504454743814489);
                      if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:0.0:1.0 */
                        if (double_attr(0) <= 0.5544444444444445) {
                          add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0 */
                                     0.36145595799965363);
                          if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:0.0:1.0:0.0 */
                            if (double_attr(0) <= 0.5068742985409652) {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:0 */
                                         -0.33262236134902645);
                              if (defined_attr(1)) {  /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:0.0 */
                                if (double_attr(1) <= 0.14035260514133754) {
                                  add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:0.0:0 */
                                             0.5130963690226028);
                                } else {
                                  add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:0.0:1 */
                                             -0.5367125261221793);
                                }
                              }
                            } else {
                              add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:1 */
                                         0.38953315714495745);
                              if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:1.0 */
                                if (double_attr(0) <= 0.5408333333333333) {
                                  add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:1.0:0 */
                                             0.553271015981667);
                                } else {
                                  add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:0.0:1.0:1 */
                                             -0.35885225894636014);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.1:0.0:1.0:1 */
                                     -2.1561084960696273);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:1.0:0.1:1 */
                             -0.34946135035731785);
                  if (defined_attr(1)) {  /* R.0:1.1:1.0:0.1:1.0 */
                    if (double_attr(1) <= 0.27555037763136747) {
                      add_pred(   /* R.0:1.1:1.0:0.1:1.0:0 */
                                 -0.0989851552910659);
                      if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:1.0:0.0 */
                        if (double_attr(0) <= 0.5163978494623656) {
                          add_pred(   /* R.0:1.1:1.0:0.1:1.0:0.0:0 */
                                     -0.6697904027828718);
                        } else {
                          add_pred(   /* R.0:1.1:1.0:0.1:1.0:0.0:1 */
                                     0.027658165147977216);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.1:1.0:1 */
                                 -2.5092245810379206);
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:1.1:1.0:0.1:1.1 */
                    if (double_attr(0) <= 0.5077561327561327) {
                      add_pred(   /* R.0:1.1:1.0:0.1:1.1:0 */
                                 -2.3126962235152395);
                    } else {
                      add_pred(   /* R.0:1.1:1.0:0.1:1.1:1 */
                                 -0.053020842202999796);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:1.1:1.0:1 */
                         3.8024242212637813);
            }
          }
          if (defined_attr(0)) {  /* R.0:1.1:1.1 */
            if (double_attr(0) <= 0.5107638888888888) {
              add_pred(   /* R.0:1.1:1.1:0 */
                         -0.4915538402489716);
              if (defined_attr(2)) {  /* R.0:1.1:1.1:0.0 */
                if (double_attr(2) <= 0.5117647349834442) {
                  add_pred(   /* R.0:1.1:1.1:0.0:0 */
                             -0.5336661741020927);
                  if (defined_attr(0)) {  /* R.0:1.1:1.1:0.0:0.0 */
                    if (double_attr(0) <= 0.49739583333333337) {
                      add_pred(   /* R.0:1.1:1.1:0.0:0.0:0 */
                                 -1.1394366261770075);
                    } else {
                      add_pred(   /* R.0:1.1:1.1:0.0:0.0:1 */
                                 0.0646839813318428);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:1.1:0.0:1 */
                             0.46067497030961657);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:1.1:1 */
                         0.16159033936263212);
              if (defined_attr(2)) {  /* R.0:1.1:1.1:1.0 */
                if (double_attr(2) <= 0.42941176891326904) {
                  add_pred(   /* R.0:1.1:1.1:1.0:0 */
                             0.29568490719742047);
                  if (defined_attr(2)) {  /* R.0:1.1:1.1:1.0:0.0 */
                    if (double_attr(2) <= 0.37843137979507446) {
                      add_pred(   /* R.0:1.1:1.1:1.0:0.0:0 */
                                 -0.41227313226353013);
                    } else {
                      add_pred(   /* R.0:1.1:1.1:1.0:0.0:1 */
                                 0.2741887710194084);
                      if (defined_attr(1)) {  /* R.0:1.1:1.1:1.0:0.0:1.0 */
                        if (double_attr(1) <= 0.16420499603489294) {
                          add_pred(   /* R.0:1.1:1.1:1.0:0.0:1.0:0 */
                                     0.4843095568668458);
                        } else {
                          add_pred(   /* R.0:1.1:1.1:1.0:0.0:1.0:1 */
                                     0.04198330216800213);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:1.1:1.0:1 */
                             -0.035625461126077056);
                  if (defined_attr(0)) {  /* R.0:1.1:1.1:1.0:1.0 */
                    if (double_attr(0) <= 0.5404918032786885) {
                      add_pred(   /* R.0:1.1:1.1:1.0:1.0:0 */
                                 0.06952173058997763);
                    } else {
                      add_pred(   /* R.0:1.1:1.1:1.0:1.0:1 */
                                 -0.12171799421308362);
                      if (defined_attr(0)) {  /* R.0:1.1:1.1:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.6996527777777778) {
                          add_pred(   /* R.0:1.1:1.1:1.0:1.0:1.0:0 */
                                     -0.07283728616652993);
                          if (defined_attr(2)) {  /* R.0:1.1:1.1:1.0:1.0:1.0:0.0 */
                            if (double_attr(2) <= 0.5705882608890533) {
                              add_pred(   /* R.0:1.1:1.1:1.0:1.0:1.0:0.0:0 */
                                         -0.02876739234246629);
                            } else {
                              add_pred(   /* R.0:1.1:1.1:1.0:1.0:1.0:0.0:1 */
                                         -1.6958189794196616);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.1:1.1:1.0:1.0:1.0:1 */
                                     1.5758448918505592);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  if (defined_attr(0)) {  /* R.1 */
    if (double_attr(0) <= 0.08874824191279887) {
      add_pred(   /* R.1:0 */
                 1.8385203281326725);
      if (defined_attr(1)) {  /* R.1:0.0 */
        if (double_attr(1) <= 0.19700701597253323) {
          add_pred(   /* R.1:0.0:0 */
                     -0.2733553450702695);
          if (defined_attr(1)) {  /* R.1:0.0:0.0 */
            if (double_attr(1) <= 0.09789178829426506) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         -0.3544393595169389);
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         0.5923909573966395);
              if (defined_attr(2)) {  /* R.1:0.0:0.0:1.0 */
                if (double_attr(2) <= 0.47647058963775635) {
                  add_pred(   /* R.1:0.0:0.0:1.0:0 */
                             1.8570933974628543);
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.0:1 */
                             0.04022903163331819);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     2.307168221538716);
          if (defined_attr(2)) {  /* R.1:0.0:1.0 */
            if (double_attr(2) <= 0.4686274528503418) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         -0.770031108838289);
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         3.3493028328702485);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 -0.0824536179051316);
      if (defined_attr(1)) {  /* R.1:1.0 */
        if (double_attr(1) <= 0.22140130861504909) {
          add_pred(   /* R.1:1.0:0 */
                     0.18662387257177332);
        } else {
          add_pred(   /* R.1:1.0:1 */
                     -0.9797121565755842);
          if (defined_attr(0)) {  /* R.1:1.0:1.0 */
            if (double_attr(0) <= 0.673611111111111) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         -0.623103379212202);
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         2.8982846605290944);
            }
          }
          if (defined_attr(1)) {  /* R.1:1.0:1.1 */
            if (double_attr(1) <= 0.23766434020451224) {
              add_pred(   /* R.1:1.0:1.1:0 */
                         0.4690593769675291);
            } else {
              add_pred(   /* R.1:1.0:1.1:1 */
                         -0.18771449287096664);
            }
          }
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.2 */
    if (double_attr(2) <= 0.9941176474094391) {
      add_pred(   /* R.2:0 */
                 -0.0522299365725184);
      if (defined_attr(0)) {  /* R.2:0.0 */
        if (double_attr(0) <= 0.41540404040404044) {
          add_pred(   /* R.2:0.0:0 */
                     -0.693218903094815);
          if (defined_attr(0)) {  /* R.2:0.0:0.0 */
            if (double_attr(0) <= 0.0979614067849362) {
              add_pred(   /* R.2:0.0:0.0:0 */
                         0.15687886439119725);
              if (defined_attr(1)) {  /* R.2:0.0:0.0:0.0 */
                if (double_attr(1) <= 0.08298669244179022) {
                  add_pred(   /* R.2:0.0:0.0:0.0:0 */
                             -0.8541179160077602);
                } else {
                  add_pred(   /* R.2:0.0:0.0:0.0:1 */
                             0.5942863920014564);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:0.0:1 */
                         -0.5315031504597469);
              if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0 */
                if (double_attr(1) <= 0.0790737142984748) {
                  add_pred(   /* R.2:0.0:0.0:1.0:0 */
                             -0.0049863338604658036);
                  if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0 */
                    if (double_attr(2) <= 0.46078431606292725) {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:0 */
                                 -0.6318165394386451);
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:1 */
                                 0.16672623548025461);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:1.0 */
                        if (double_attr(2) <= 0.5588235557079315) {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:0 */
                                     0.2522259501077232);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:0.0 */
                            if (double_attr(1) <= 0.015209345362017117) {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:0.0:0 */
                                         -1.4996870049160667);
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:0.0:1 */
                                         0.1957551975725973);
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1 */
                                     -0.7062542998894987);
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.1 */
                    if (double_attr(2) <= 0.47647058963775635) {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.1:0 */
                                 -0.23569192662252142);
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.1:1 */
                                 0.1440763754838149);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.0:1 */
                             -1.1253188666493927);
                  if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.0 */
                    if (double_attr(2) <= 0.9039215743541718) {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.0:0 */
                                 -0.6774854908141849);
                      if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:1.0:0.0 */
                        if (double_attr(0) <= 0.11785714285714285) {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0 */
                                     0.5797832887185839);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:1 */
                                     -0.8964175597772922);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.0:1 */
                                 1.7760104769750416);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.2:0.0:1 */
                     0.1727065652555827);
          if (defined_attr(0)) {  /* R.2:0.0:1.0 */
            if (double_attr(0) <= 0.5528309409888357) {
              add_pred(   /* R.2:0.0:1.0:0 */
                         0.2542632559072674);
              if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0 */
                if (double_attr(2) <= 0.6098039448261261) {
                  add_pred(   /* R.2:0.0:1.0:0.0:0 */
                             0.17509273128627356);
                  if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0 */
                    if (double_attr(2) <= 0.4960784316062927) {
                      add_pred(   /* R.2:0.0:1.0:0.0:0.0:0 */
                                 -0.040705206326646884);
                      if (defined_attr(0)) {  /* R.2:0.0:1.0:0.0:0.0:0.0 */
                        if (double_attr(0) <= 0.4811253561253561) {
                          add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0 */
                                     -0.4507111531383317);
                          if (defined_attr(1)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:0.0 */
                            if (double_attr(1) <= 0.12327316264505433) {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:0 */
                                         -0.12487841959674972);
                              if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:0.0 */
                                if (double_attr(2) <= 0.4490196108818054) {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:0.0:0 */
                                             -0.4697090403700274);
                                } else {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:0.0:1 */
                                             0.14289740565726325);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:1 */
                                         -1.2999180653516675);
                              if (defined_attr(1)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:1.0 */
                                if (double_attr(1) <= 0.13363095238095238) {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:1.0:0 */
                                             -1.1134807422164372);
                                } else {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.0:1.0:1 */
                                             0.8139298163612687);
                                }
                              }
                            }
                          }
                          if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:0.1 */
                            if (double_attr(2) <= 0.40980392694473267) {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.1:0 */
                                         -2.0666684483492532);
                            } else {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:0.1:1 */
                                         -0.06649878791094899);
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1 */
                                     0.015840394692505734);
                          if (defined_attr(1)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:1.0 */
                            if (double_attr(1) <= 0.08086312118570183) {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:0 */
                                         0.3962169460972202);
                              if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:0.0 */
                                if (double_attr(2) <= 0.4176470637321472) {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:0.0:0 */
                                             -1.0086126118455234);
                                } else {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:0.0:1 */
                                             0.2833725375995143);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1 */
                                         -0.041002611578744706);
                              if (defined_attr(0)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0 */
                                if (double_attr(0) <= 0.49739583333333337) {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0:0 */
                                             -0.40635427780093736);
                                  if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0:0.0 */
                                    if (double_attr(2) <= 0.4176470637321472) {
                                      add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0:0.0:0 */
                                                 -1.8747763436808307);
                                    } else {
                                      add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0:0.0:1 */
                                                 -0.10416517981439301);
                                    }
                                  }
                                } else {
                                  add_pred(   /* R.2:0.0:1.0:0.0:0.0:0.0:1.0:1.0:1 */
                                             -0.0037923787843939815);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:1.0:0.0:0.0:1 */
                                 0.4280087773292768);
                      if (defined_attr(1)) {  /* R.2:0.0:1.0:0.0:0.0:1.0 */
                        if (double_attr(1) <= 0.0459776864357017) {
                          add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:0 */
                                     -0.6466155671406989);
                          if (defined_attr(2)) {  /* R.2:0.0:1.0:0.0:0.0:1.0:0.0 */
                            if (double_attr(2) <= 0.5431372821331024) {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:0.0:0 */
                                         0.02050039814951079);
                            } else {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:0.0:1 */
                                         -2.2053539251150105);
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:1 */
                                     0.17036544086433045);
                          if (defined_attr(0)) {  /* R.2:0.0:1.0:0.0:0.0:1.0:1.0 */
                            if (double_attr(0) <= 0.5404918032786885) {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:1.0:0 */
                                         0.16790881861136023);
                            } else {
                              add_pred(   /* R.2:0.0:1.0:0.0:0.0:1.0:1.0:1 */
                                         -0.2943625440617193);
                            }
                          }
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:1.0:0.0:1 */
                             -2.5513240196570783);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:1.0:1 */
                         -0.37467559655926996);
              if (defined_attr(1)) {  /* R.2:0.0:1.0:1.0 */
                if (double_attr(1) <= 0.07762805490458655) {
                  add_pred(   /* R.2:0.0:1.0:1.0:0 */
                             0.31904302621240443);
                } else {
                  add_pred(   /* R.2:0.0:1.0:1.0:1 */
                             -0.49537697479761167);
                  if (defined_attr(0)) {  /* R.2:0.0:1.0:1.0:1.0 */
                    if (double_attr(0) <= 0.5790217068093964) {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:0 */
                                 0.17815331557928002);
                      if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:1.0:0.0 */
                        if (double_attr(2) <= 0.5392157137393951) {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:0.0:0 */
                                     0.03498905599046843);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:0.0:1 */
                                     -1.0867965517355596);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:1 */
                                 -0.8703363569250809);
                      if (defined_attr(0)) {  /* R.2:0.0:1.0:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.7537878787878787) {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:1.0:0 */
                                     -2.3098026831366383);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:1.0:1 */
                                     5.256501567795236);
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:1.1 */
                    if (double_attr(2) <= 0.4529411792755127) {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.1:0 */
                                 0.4553690203337543);
                      if (defined_attr(1)) {  /* R.2:0.0:1.0:1.0:1.1:0.0 */
                        if (double_attr(1) <= 0.20976190476190476) {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.1:0.0:0 */
                                     0.2693799487302194);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.1:0.0:1 */
                                     -0.5707314196513197);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.1:1 */
                                 -0.37754181338183834);
                    }
                  }
                }
              }
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.2:0.1 */
        if (double_attr(2) <= 0.5784313976764679) {
          add_pred(   /* R.2:0.1:0 */
                     0.052669945644941464);
          if (defined_attr(2)) {  /* R.2:0.1:0.0 */
            if (double_attr(2) <= 0.3588235378265381) {
              add_pred(   /* R.2:0.1:0.0:0 */
                         -1.5166125765980731);
              if (defined_attr(2)) {  /* R.2:0.1:0.0:0.0 */
                if (double_attr(2) <= 0.30392158031463623) {
                  add_pred(   /* R.2:0.1:0.0:0.0:0 */
                             -2.174541319884188);
                } else {
                  add_pred(   /* R.2:0.1:0.0:0.0:1 */
                             -0.372990072861523);
                }
              }
            } else {
              add_pred(   /* R.2:0.1:0.0:1 */
                         0.03873528920988315);
            }
          }
          if (defined_attr(2)) {  /* R.2:0.1:0.1 */
            if (double_attr(2) <= 0.30392158031463623) {
              add_pred(   /* R.2:0.1:0.1:0 */
                         -1.6680207276300039);
            } else {
              add_pred(   /* R.2:0.1:0.1:1 */
                         0.01635845250784192);
            }
          }
        } else {
          add_pred(   /* R.2:0.1:1 */
                     -0.5524266401965688);
          if (defined_attr(2)) {  /* R.2:0.1:1.0 */
            if (double_attr(2) <= 0.9901960790157318) {
              add_pred(   /* R.2:0.1:1.0:0 */
                         -0.40377891964102713);
              if (defined_attr(1)) {  /* R.2:0.1:1.0:0.0 */
                if (double_attr(1) <= 0.1462044395724856) {
                  add_pred(   /* R.2:0.1:1.0:0.0:0 */
                             -0.552368823180994);
                  if (defined_attr(2)) {  /* R.2:0.1:1.0:0.0:0.0 */
                    if (double_attr(2) <= 0.5901961028575897) {
                      add_pred(   /* R.2:0.1:1.0:0.0:0.0:0 */
                                 0.4013855277112027);
                    } else {
                      add_pred(   /* R.2:0.1:1.0:0.0:0.0:1 */
                                 -0.4398539589966968);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.1:1.0:0.0:1 */
                             0.531605077265559);
                  if (defined_attr(0)) {  /* R.2:0.1:1.0:0.0:1.0 */
                    if (double_attr(0) <= 0.11031746031746031) {
                      add_pred(   /* R.2:0.1:1.0:0.0:1.0:0 */
                                 1.1797537979983488);
                      if (defined_attr(1)) {  /* R.2:0.1:1.0:0.0:1.0:0.0 */
                        if (double_attr(1) <= 0.19597297297297298) {
                          add_pred(   /* R.2:0.1:1.0:0.0:1.0:0.0:0 */
                                     0.13208776912555426);
                        } else {
                          add_pred(   /* R.2:0.1:1.0:0.0:1.0:0.0:1 */
                                     1.733492382674163);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.1:1.0:0.0:1.0:1 */
                                 -1.0901440468962704);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.2:0.1:1.0:1 */
                         0.693929317049292);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.2:1 */
                 1.6588847419195127);
      if (defined_attr(0)) {  /* R.2:1.0 */
        if (double_attr(0) <= 0.6875) {
          add_pred(   /* R.2:1.0:0 */
                     0.3429828222976517);
          if (defined_attr(0)) {  /* R.2:1.0:0.0 */
            if (double_attr(0) <= 0.475) {
              add_pred(   /* R.2:1.0:0.0:0 */
                         0.46073598126190973);
            } else {
              add_pred(   /* R.2:1.0:0.0:1 */
                         -1.4201763504402865);
              if (defined_attr(1)) {  /* R.2:1.0:0.0:1.0 */
                if (double_attr(1) <= 0.045098039215686274) {
                  add_pred(   /* R.2:1.0:0.0:1.0:0 */
                             -0.008819181433938093);
                } else {
                  add_pred(   /* R.2:1.0:0.0:1.0:1 */
                             -2.428191067176898);
                }
              }
              if (defined_attr(0)) {  /* R.2:1.0:0.0:1.1 */
                if (double_attr(0) <= 0.5773809523809523) {
                  add_pred(   /* R.2:1.0:0.0:1.1:0 */
                             -1.247140709619951);
                } else {
                  add_pred(   /* R.2:1.0:0.0:1.1:1 */
                             0.2324304554763732);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.2:1.0:1 */
                     2.258776260738757);
        }
      }
    }
  }
  if (defined_attr(0)) {  /* R.3 */
    if (double_attr(0) <= 0.9591666666666667) {
      add_pred(   /* R.3:0 */
                 -0.005439640313738948);
    } else {
      add_pred(   /* R.3:1 */
                 2.2428847172557065);
    }
  }
  return finalize_pred();
}
