/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:
  double predict(void **attr, double *ret)
The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.
Specifically, these pointers are:
     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V
The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).
These scores correspond to the classes as follows:
            index       class name
           ------------------------
               0        non-buoy
               1        buoy
This classifier was automatically generated by jboost on
Fri Dec 11 18:58:04 GMT-00:08 2009.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <values.h>
#include "strlcpy.h"
typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))
#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};
static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;
static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}
#define more_tokens()  (cur_word <= num_words - pattern_len)
#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}
static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;
  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);
  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}
static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;
  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }
  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= MAXINT - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}
double predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;
  Prediction_t p;
  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }
  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;
    while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen((char*)attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }
  reset_pred();
  add_pred(   /* R */
             0.2895938885913509);
  if (defined_attr(0)) {  /* R.0 */
    if (double_attr(0) <= 81.5) {
      add_pred(   /* R.0:0 */
                 -1.1429521957653708);
      if (defined_attr(1)) {  /* R.0:0.0 */
        if (double_attr(1) <= 66.5) {
          add_pred(   /* R.0:0.0:0 */
                     -0.16813774766226458);
        } else {
          add_pred(   /* R.0:0.0:1 */
                     -4.191356747539837);
        }
      }
      if (defined_attr(1)) {  /* R.0:0.1 */
        if (double_attr(1) <= 33.5) {
          add_pred(   /* R.0:0.1:0 */
                     0.5841705151294718);
          if (defined_attr(2)) {  /* R.0:0.1:0.0 */
            if (double_attr(2) <= 100.5) {
              add_pred(   /* R.0:0.1:0.0:0 */
                         -1.7499585375151192);
            } else {
              add_pred(   /* R.0:0.1:0.0:1 */
                         0.17215538362304988);
              if (defined_attr(1)) {  /* R.0:0.1:0.0:1.0 */
                if (double_attr(1) <= 21.5) {
                  add_pred(   /* R.0:0.1:0.0:1.0:0 */
                             0.17421561591079784);
                  if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0:0.0 */
                    if (double_attr(2) <= 108.5) {
                      add_pred(   /* R.0:0.1:0.0:1.0:0.0:0 */
                                 -0.72145864354411);
                    } else {
                      add_pred(   /* R.0:0.1:0.0:1.0:0.0:1 */
                                 0.13419131259791772);
                      if (defined_attr(1)) {  /* R.0:0.1:0.0:1.0:0.0:1.0 */
                        if (double_attr(1) <= 7.5) {
                          add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:0 */
                                     0.3314411396014159);
                          if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:0.0:1.0:0.0 */
                            if (double_attr(0) <= 73.5) {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:0.0:0 */
                                         0.11717118810606678);
                            } else {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:0.0:1 */
                                         1.110340868792048);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:1 */
                                     0.046645817356992095);
                          if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:0.0:1.0:1.0 */
                            if (double_attr(0) <= 6.5) {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:1.0:0 */
                                         -0.7427545970833109);
                              if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0:0.0:1.0:1.0:0.0 */
                                if (double_attr(2) <= 119.5) {
                                  add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:1.0:0.0:0 */
                                             0.07018265845006838);
                                } else {
                                  add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:1.0:0.0:1 */
                                             -1.8720922979778643);
                                }
                              }
                            } else {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.0:1.0:1.0:1 */
                                         0.07836390171872096);
                            }
                          }
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0:0.1 */
                    if (double_attr(2) <= 114.5) {
                      add_pred(   /* R.0:0.1:0.0:1.0:0.1:0 */
                                 -0.15262310270531929);
                    } else {
                      add_pred(   /* R.0:0.1:0.0:1.0:0.1:1 */
                                 0.08894360516636722);
                      if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0:0.1:1.0 */
                        if (double_attr(2) <= 132.5) {
                          add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:0 */
                                     0.10461068426745657);
                        } else {
                          add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:1 */
                                     -0.20436271733021302);
                          if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:0.1:1.0:1.0 */
                            if (double_attr(0) <= 73.5) {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:1.0:0 */
                                         -0.2023883074934103);
                              if (defined_attr(1)) {  /* R.0:0.1:0.0:1.0:0.1:1.0:1.0:0.0 */
                                if (double_attr(1) <= 2.5) {
                                  add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:1.0:0.0:0 */
                                             0.4651654094736932);
                                } else {
                                  add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:1.0:0.0:1 */
                                             -0.2532170490774971);
                                }
                              }
                            } else {
                              add_pred(   /* R.0:0.1:0.0:1.0:0.1:1.0:1.0:1 */
                                         0.6215850685021118);
                            }
                          }
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.1:0.0:1.0:1 */
                             -0.0702253102014124);
                  if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:1.0 */
                    if (double_attr(0) <= 48.0) {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.0:0 */
                                 0.013657563129954945);
                      if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0:1.0:0.0 */
                        if (double_attr(2) <= 112.5) {
                          add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:0 */
                                     0.24982816310988348);
                          if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:1.0:0.0:0.0 */
                            if (double_attr(0) <= 28.5) {
                              add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:0.0:0 */
                                         0.2707696930148351);
                            } else {
                              add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:0.0:1 */
                                         -0.48523425691658995);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1 */
                                     -0.0667804093797565);
                          if (defined_attr(1)) {  /* R.0:0.1:0.0:1.0:1.0:0.0:1.0 */
                            if (double_attr(1) <= 31.5) {
                              add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1.0:0 */
                                         6.447254444838697E-4);
                            } else {
                              add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1.0:1 */
                                         -0.27464168478282147);
                              if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:1.0:0.0:1.0:1.0 */
                                if (double_attr(0) <= 18.0) {
                                  add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1.0:1.0:0 */
                                             -1.2528593464973483);
                                } else {
                                  add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1.0:1.0:1 */
                                             -0.0787536377805527);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.0:1 */
                                 -2.3712780001295055);
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:1.1 */
                    if (double_attr(0) <= 15.5) {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.1:0 */
                                 -1.3144331777512133);
                    } else {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.1:1 */
                                 -0.0011640046498499971);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.1:1 */
                     -0.5872316300276833);
          if (defined_attr(0)) {  /* R.0:0.1:1.0 */
            if (double_attr(0) <= 18.5) {
              add_pred(   /* R.0:0.1:1.0:0 */
                         -1.805652025611418);
              if (defined_attr(2)) {  /* R.0:0.1:1.0:0.0 */
                if (double_attr(2) <= 119.5) {
                  add_pred(   /* R.0:0.1:1.0:0.0:0 */
                             0.16250405769028425);
                } else {
                  add_pred(   /* R.0:0.1:1.0:0.0:1 */
                             -1.0603505810517828);
                }
              }
              if (defined_attr(0)) {  /* R.0:0.1:1.0:0.1 */
                if (double_attr(0) <= 15.5) {
                  add_pred(   /* R.0:0.1:1.0:0.1:0 */
                             -1.8376774039537118);
                } else {
                  add_pred(   /* R.0:0.1:1.0:0.1:1 */
                             0.08377805657462307);
                }
              }
            } else {
              add_pred(   /* R.0:0.1:1.0:1 */
                         -0.040920001311093544);
              if (defined_attr(0)) {  /* R.0:0.1:1.0:1.0 */
                if (double_attr(0) <= 31.5) {
                  add_pred(   /* R.0:0.1:1.0:1.0:0 */
                             0.09060958018822055);
                } else {
                  add_pred(   /* R.0:0.1:1.0:1.0:1 */
                             -1.3706569010792962);
                }
              }
              if (defined_attr(0)) {  /* R.0:0.1:1.0:1.1 */
                if (double_attr(0) <= 28.5) {
                  add_pred(   /* R.0:0.1:1.0:1.1:0 */
                             0.08598828598462546);
                  if (defined_attr(0)) {  /* R.0:0.1:1.0:1.1:0.0 */
                    if (double_attr(0) <= 21.5) {
                      add_pred(   /* R.0:0.1:1.0:1.1:0.0:0 */
                                 -0.31650117071572215);
                    } else {
                      add_pred(   /* R.0:0.1:1.0:1.1:0.0:1 */
                                 0.19404924136955626);
                      if (defined_attr(2)) {  /* R.0:0.1:1.0:1.1:0.0:1.0 */
                        if (double_attr(2) <= 130.5) {
                          add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:0 */
                                     0.02433083152778267);
                        } else {
                          add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:1 */
                                     0.8223242322176865);
                          if (defined_attr(1)) {  /* R.0:0.1:1.0:1.1:0.0:1.0:1.0 */
                            if (double_attr(1) <= 54.5) {
                              add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:1.0:0 */
                                         0.5195909198294791);
                              if (defined_attr(0)) {  /* R.0:0.1:1.0:1.1:0.0:1.0:1.0:0.0 */
                                if (double_attr(0) <= 22.5) {
                                  add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:1.0:0.0:0 */
                                             -1.126181598326109);
                                } else {
                                  add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:1.0:0.0:1 */
                                             0.2816241926583363);
                                }
                              }
                            } else {
                              add_pred(   /* R.0:0.1:1.0:1.1:0.0:1.0:1.0:1 */
                                         -2.060118908020112);
                            }
                          }
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.0:0.1:1.0:1.1:0.1 */
                    if (double_attr(2) <= 109.5) {
                      add_pred(   /* R.0:0.1:1.0:1.1:0.1:0 */
                                 0.19015757852689263);
                    } else {
                      add_pred(   /* R.0:0.1:1.0:1.1:0.1:1 */
                                 -0.0535807172331993);
                      if (defined_attr(2)) {  /* R.0:0.1:1.0:1.1:0.1:1.0 */
                        if (double_attr(2) <= 121.5) {
                          add_pred(   /* R.0:0.1:1.0:1.1:0.1:1.0:0 */
                                     -0.1177971276688962);
                        } else {
                          add_pred(   /* R.0:0.1:1.0:1.1:0.1:1.0:1 */
                                     0.07772256750290364);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.1:1.0:1.1:1 */
                             -0.5216080810038436);
                  if (defined_attr(1)) {  /* R.0:0.1:1.0:1.1:1.0 */
                    if (double_attr(1) <= 48.5) {
                      add_pred(   /* R.0:0.1:1.0:1.1:1.0:0 */
                                 -0.07463037265357772);
                    } else {
                      add_pred(   /* R.0:0.1:1.0:1.1:1.0:1 */
                                 -2.81758829564638);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.0:0.1:1.1 */
            if (double_attr(1) <= 36.5) {
              add_pred(   /* R.0:0.1:1.1:0 */
                         0.3509845475314376);
            } else {
              add_pred(   /* R.0:0.1:1.1:1 */
                         -0.0995515782619484);
              if (defined_attr(2)) {  /* R.0:0.1:1.1:1.0 */
                if (double_attr(2) <= 112.5) {
                  add_pred(   /* R.0:0.1:1.1:1.0:0 */
                             0.12518749364247278);
                } else {
                  add_pred(   /* R.0:0.1:1.1:1.0:1 */
                             -0.13598210032610858);
                }
              }
              if (defined_attr(0)) {  /* R.0:0.1:1.1:1.1 */
                if (double_attr(0) <= 27.5) {
                  add_pred(   /* R.0:0.1:1.1:1.1:0 */
                             0.015359793613989857);
                } else {
                  add_pred(   /* R.0:0.1:1.1:1.1:1 */
                             -0.356314613477705);
                  if (defined_attr(0)) {  /* R.0:0.1:1.1:1.1:1.0 */
                    if (double_attr(0) <= 34.5) {
                      add_pred(   /* R.0:0.1:1.1:1.1:1.0:0 */
                                 -0.1824983878831002);
                    } else {
                      add_pred(   /* R.0:0.1:1.1:1.1:1.0:1 */
                                 -1.830875242721042);
                    }
                  }
                  if (defined_attr(1)) {  /* R.0:0.1:1.1:1.1:1.1 */
                    if (double_attr(1) <= 48.5) {
                      add_pred(   /* R.0:0.1:1.1:1.1:1.1:0 */
                                 -0.03593174200836577);
                    } else {
                      add_pred(   /* R.0:0.1:1.1:1.1:1.1:1 */
                                 -0.7153804430794685);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.0:0.1:1.2 */
            if (double_attr(1) <= 42.5) {
              add_pred(   /* R.0:0.1:1.2:0 */
                         0.13900248411101168);
              if (defined_attr(2)) {  /* R.0:0.1:1.2:0.0 */
                if (double_attr(2) <= 109.5) {
                  add_pred(   /* R.0:0.1:1.2:0.0:0 */
                             0.4574947046997588);
                } else {
                  add_pred(   /* R.0:0.1:1.2:0.0:1 */
                             -0.0022515025794818374);
                }
              }
            } else {
              add_pred(   /* R.0:0.1:1.2:1 */
                         -0.08001914582469358);
            }
          }
          if (defined_attr(2)) {  /* R.0:0.1:1.3 */
            if (double_attr(2) <= 155.5) {
              add_pred(   /* R.0:0.1:1.3:0 */
                         0.0225043144519954);
            } else {
              add_pred(   /* R.0:0.1:1.3:1 */
                         -1.8443196908294042);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 2.0542443183164907);
      if (defined_attr(2)) {  /* R.0:1.0 */
        if (double_attr(2) <= 244.5) {
          add_pred(   /* R.0:1.0:0 */
                     -0.5699688856819132);
          if (defined_attr(0)) {  /* R.0:1.0:0.0 */
            if (double_attr(0) <= 94.5) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -0.6572764608015806);
              if (defined_attr(1)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(1) <= 16.5) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             0.0494166012310426);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             -2.8983889145747748);
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:0.1 */
                if (double_attr(1) <= 15.5) {
                  add_pred(   /* R.0:1.0:0.0:0.1:0 */
                             0.19733758733400206);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.1:1 */
                             -0.9399894707090485);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         -0.028253000877167794);
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     0.7438089108111148);
          if (defined_attr(1)) {  /* R.0:1.0:1.0 */
            if (double_attr(1) <= 19.5) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -0.14899323197044326);
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         3.111410613873896);
            }
          }
          if (defined_attr(1)) {  /* R.0:1.0:1.1 */
            if (double_attr(1) <= 15.5) {
              add_pred(   /* R.0:1.0:1.1:0 */
                         -0.15246604545126322);
            } else {
              add_pred(   /* R.0:1.0:1.1:1 */
                         0.930955116312989);
            }
          }
        }
      }
    }
  }
  if (defined_attr(0)) {  /* R.1 */
    if (double_attr(0) <= 102.5) {
      add_pred(   /* R.1:0 */
                 -0.07508130401279703);
      if (defined_attr(1)) {  /* R.1:0.0 */
        if (double_attr(1) <= 52.5) {
          add_pred(   /* R.1:0.0:0 */
                     0.13620145751544488);
          if (defined_attr(2)) {  /* R.1:0.0:0.0 */
            if (double_attr(2) <= 96.5) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         -0.7429934795202741);
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         0.01737507365424088);
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     -0.829077285966002);
          if (defined_attr(1)) {  /* R.1:0.0:1.0 */
            if (double_attr(1) <= 83.5) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         -0.36628338452779463);
              if (defined_attr(2)) {  /* R.1:0.0:1.0:0.0 */
                if (double_attr(2) <= 229.5) {
                  add_pred(   /* R.1:0.0:1.0:0.0:0 */
                             -0.006789806876514657);
                } else {
                  add_pred(   /* R.1:0.0:1.0:0.0:1 */
                             2.03520764477118);
                }
              }
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         -3.1205369742663285);
            }
          }
          if (defined_attr(1)) {  /* R.1:0.0:1.1 */
            if (double_attr(1) <= 58.5) {
              add_pred(   /* R.1:0.0:1.1:0 */
                         0.18891745111935138);
            } else {
              add_pred(   /* R.1:0.0:1.1:1 */
                         -0.31874368239086903);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 1.597265112886461);
      if (defined_attr(1)) {  /* R.1:1.0 */
        if (double_attr(1) <= 50.5) {
          add_pred(   /* R.1:1.0:0 */
                     -0.36877171249135965);
          if (defined_attr(0)) {  /* R.1:1.0:0.0 */
            if (double_attr(0) <= 175.5) {
              add_pred(   /* R.1:1.0:0.0:0 */
                         0.03379239528691978);
            } else {
              add_pred(   /* R.1:1.0:0.0:1 */
                         -1.8337593790366153);
            }
          }
        } else {
          add_pred(   /* R.1:1.0:1 */
                     2.206114840670509);
          if (defined_attr(2)) {  /* R.1:1.0:1.0 */
            if (double_attr(2) <= 119.5) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         -0.8549282731137913);
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         3.507715717508903);
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.1:1.1 */
        if (double_attr(0) <= 154.5) {
          add_pred(   /* R.1:1.1:0 */
                     0.45109937211728446);
          if (defined_attr(1)) {  /* R.1:1.1:0.0 */
            if (double_attr(1) <= 24.5) {
              add_pred(   /* R.1:1.1:0.0:0 */
                         -0.27147632877339134);
            } else {
              add_pred(   /* R.1:1.1:0.0:1 */
                         0.8502834150350225);
              if (defined_attr(2)) {  /* R.1:1.1:0.0:1.0 */
                if (double_attr(2) <= 73.0) {
                  add_pred(   /* R.1:1.1:0.0:1.0:0 */
                             -1.7701566813249467);
                } else {
                  add_pred(   /* R.1:1.1:0.0:1.0:1 */
                             0.6320232350347946);
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.1:1.1:0.1 */
            if (double_attr(1) <= 11.5) {
              add_pred(   /* R.1:1.1:0.1:0 */
                         -0.5650528745813342);
            } else {
              add_pred(   /* R.1:1.1:0.1:1 */
                         0.1755200852961076);
            }
          }
        } else {
          add_pred(   /* R.1:1.1:1 */
                     -1.9877510957537476);
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.2 */
    if (double_attr(2) <= 253.5) {
      add_pred(   /* R.2:0 */
                 -0.011925011491667048);
      if (defined_attr(0)) {  /* R.2:0.0 */
        if (double_attr(0) <= 45.5) {
          add_pred(   /* R.2:0.0:0 */
                     0.156402908581741);
          if (defined_attr(0)) {  /* R.2:0.0:0.0 */
            if (double_attr(0) <= 16.5) {
              add_pred(   /* R.2:0.0:0.0:0 */
                         -0.6860066410013547);
              if (defined_attr(1)) {  /* R.2:0.0:0.0:0.0 */
                if (double_attr(1) <= 11.5) {
                  add_pred(   /* R.2:0.0:0.0:0.0:0 */
                             0.7569283697452178);
                } else {
                  add_pred(   /* R.2:0.0:0.0:0.0:1 */
                             -1.2595490271572034);
                  if (defined_attr(0)) {  /* R.2:0.0:0.0:0.0:1.0 */
                    if (double_attr(0) <= 10.5) {
                      add_pred(   /* R.2:0.0:0.0:0.0:1.0:0 */
                                 -2.1024000094177326);
                    } else {
                      add_pred(   /* R.2:0.0:0.0:0.0:1.0:1 */
                                 -0.23337462521083574);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:0.0:1.0:1.0 */
                        if (double_attr(2) <= 118.5) {
                          add_pred(   /* R.2:0.0:0.0:0.0:1.0:1.0:0 */
                                     0.6673119587479841);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:0.0:1.0:1.0:1 */
                                     0.016456730131875992);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(2)) {  /* R.2:0.0:0.0:0.1 */
                if (double_attr(2) <= 124.5) {
                  add_pred(   /* R.2:0.0:0.0:0.1:0 */
                             0.4690010183184604);
                } else {
                  add_pred(   /* R.2:0.0:0.0:0.1:1 */
                             -0.5344221263270471);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:0.0:1 */
                         0.20366901622901942);
              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0 */
                if (double_attr(2) <= 150.5) {
                  add_pred(   /* R.2:0.0:0.0:1.0:0 */
                             0.1481868655228433);
                  if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0 */
                    if (double_attr(2) <= 126.5) {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:0 */
                                 -0.012030661763621317);
                      if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:0.0:0.0 */
                        if (double_attr(0) <= 33.5) {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:0 */
                                     0.015381901368504076);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:1 */
                                     -0.4551837486470742);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:0.0:1.0 */
                            if (double_attr(1) <= 31.5) {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:1.0:0 */
                                         -0.08752113759549557);
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:1.0:1 */
                                         -1.5011778977947954);
                            }
                          }
                          if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:0.0:1.1 */
                            if (double_attr(2) <= 104.5) {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:1.1:0 */
                                         -2.043796950908941);
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.0:1.1:1 */
                                         -0.12173751704632678);
                            }
                          }
                        }
                      }
                      if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:0.0:0.1 */
                        if (double_attr(0) <= 30.5) {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:0 */
                                     0.03844201423870435);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:1 */
                                     -0.15367935552995907);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:0.1:1.0 */
                            if (double_attr(1) <= 30.5) {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:1.0:0 */
                                         0.013570362457513457);
                              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:0.1:1.0:0.0 */
                                if (double_attr(2) <= 112.5) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:1.0:0.0:0 */
                                             -0.46395771000780395);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:1.0:0.0:1 */
                                             0.10272574570362711);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:0.1:1.0:1 */
                                         -0.6342610633929266);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:1 */
                                 0.3624344704201445);
                      if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:0.0:1.0 */
                        if (double_attr(0) <= 20.5) {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:0 */
                                     -0.7757905710604093);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1 */
                                     0.34448947409284547);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0 */
                            if (double_attr(1) <= 16.5) {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:0 */
                                         -0.594809390714152);
                              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:0.0 */
                                if (double_attr(2) <= 138.5) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:0.0:0 */
                                             -0.08520361942447294);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:0.0:1 */
                                             -2.2690596364330164);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1 */
                                         0.1442361352694761);
                              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0 */
                                if (double_attr(2) <= 133.5) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:0 */
                                             -0.06610932779863571);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1 */
                                             0.3671908416478567);
                                  if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0 */
                                    if (double_attr(1) <= 25.5) {
                                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:0 */
                                                 -0.3990713183928652);
                                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:0.0 */
                                        if (double_attr(2) <= 145.5) {
                                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:0.0:0 */
                                                     -0.4459580178627557);
                                        } else {
                                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:0.0:1 */
                                                     1.2901980521337946);
                                        }
                                      }
                                    } else {
                                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:1 */
                                                 0.38986143231570225);
                                      if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:1.0 */
                                        if (double_attr(1) <= 53.5) {
                                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:1.0:0 */
                                                     0.3124233000333067);
                                        } else {
                                          add_pred(   /* R.2:0.0:0.0:1.0:0.0:1.0:1.0:1.0:1.0:1.0:1 */
                                                     -1.621687888797672);
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.0:1 */
                             -1.7738582952321924);
                }
              }
              if (defined_attr(0)) {  /* R.2:0.0:0.0:1.1 */
                if (double_attr(0) <= 20.5) {
                  add_pred(   /* R.2:0.0:0.0:1.1:0 */
                             -0.19593775387760431);
                  if (defined_attr(1)) {  /* R.2:0.0:0.0:1.1:0.0 */
                    if (double_attr(1) <= 62.5) {
                      add_pred(   /* R.2:0.0:0.0:1.1:0.0:0 */
                                 -0.058169970127731244);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.1:0.0:0.0 */
                        if (double_attr(2) <= 116.5) {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:0 */
                                     0.10736072513037234);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:1 */
                                     -0.15920713004993556);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.1:0.0:0.0:1.0 */
                            if (double_attr(1) <= 43.5) {
                              add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:1.0:0 */
                                         0.024427324001473967);
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:1.0:1 */
                                         -0.40012084057437003);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.1:0.0:1 */
                                 -2.1606757887512695);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.1:1 */
                             0.044679215236455946);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.2:0.0:1 */
                     -0.6519822770155015);
          if (defined_attr(2)) {  /* R.2:0.0:1.0 */
            if (double_attr(2) <= 109.5) {
              add_pred(   /* R.2:0.0:1.0:0 */
                         -1.2639557958915797);
            } else {
              add_pred(   /* R.2:0.0:1.0:1 */
                         -0.24544686600465987);
            }
          }
          if (defined_attr(2)) {  /* R.2:0.0:1.1 */
            if (double_attr(2) <= 117.5) {
              add_pred(   /* R.2:0.0:1.1:0 */
                         -0.3332849990193896);
              if (defined_attr(0)) {  /* R.2:0.0:1.1:0.0 */
                if (double_attr(0) <= 98.5) {
                  add_pred(   /* R.2:0.0:1.1:0.0:0 */
                             -0.5623504948063678);
                  if (defined_attr(1)) {  /* R.2:0.0:1.1:0.0:0.0 */
                    if (double_attr(1) <= 12.5) {
                      add_pred(   /* R.2:0.0:1.1:0.0:0.0:0 */
                                 0.0319332572025834);
                    } else {
                      add_pred(   /* R.2:0.0:1.1:0.0:0.0:1 */
                                 -0.9568001045638339);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:1.1:0.0:1 */
                             0.14452893107027495);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:1.1:1 */
                         0.06550813732827533);
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.2:0.1 */
        if (double_attr(2) <= 145.5) {
          add_pred(   /* R.2:0.1:0 */
                     0.01208824126050903);
          if (defined_attr(2)) {  /* R.2:0.1:0.0 */
            if (double_attr(2) <= 91.5) {
              add_pred(   /* R.2:0.1:0.0:0 */
                         -1.506947205272573);
            } else {
              add_pred(   /* R.2:0.1:0.0:1 */
                         0.02405866263651991);
            }
          }
          if (defined_attr(0)) {  /* R.2:0.1:0.1 */
            if (double_attr(0) <= 166.0) {
              add_pred(   /* R.2:0.1:0.1:0 */
                         0.012988800657443792);
            } else {
              add_pred(   /* R.2:0.1:0.1:1 */
                         -1.702143340187814);
            }
          }
        } else {
          add_pred(   /* R.2:0.1:1 */
                     -0.6700945528778356);
          if (defined_attr(2)) {  /* R.2:0.1:1.0 */
            if (double_attr(2) <= 252.5) {
              add_pred(   /* R.2:0.1:1.0:0 */
                         -0.39449732077899013);
              if (defined_attr(1)) {  /* R.2:0.1:1.0:0.0 */
                if (double_attr(1) <= 33.5) {
                  add_pred(   /* R.2:0.1:1.0:0.0:0 */
                             -0.48173757772678516);
                  if (defined_attr(2)) {  /* R.2:0.1:1.0:0.0:0.0 */
                    if (double_attr(2) <= 152.5) {
                      add_pred(   /* R.2:0.1:1.0:0.0:0.0:0 */
                                 0.2709812982436689);
                    } else {
                      add_pred(   /* R.2:0.1:1.0:0.0:0.0:1 */
                                 -0.6127223486162421);
                      if (defined_attr(0)) {  /* R.2:0.1:1.0:0.0:0.0:1.0 */
                        if (double_attr(0) <= 108.5) {
                          add_pred(   /* R.2:0.1:1.0:0.0:0.0:1.0:0 */
                                     -0.6520685336952909);
                          if (defined_attr(0)) {  /* R.2:0.1:1.0:0.0:0.0:1.0:0.0 */
                            if (double_attr(0) <= 97.5) {
                              add_pred(   /* R.2:0.1:1.0:0.0:0.0:1.0:0.0:0 */
                                         -3.453052333417042E-4);
                            } else {
                              add_pred(   /* R.2:0.1:1.0:0.0:0.0:1.0:0.0:1 */
                                         -1.1147771035999023);
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.1:1.0:0.0:0.0:1.0:1 */
                                     0.12253350498873625);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.1:1.0:0.0:1 */
                             0.36593642121288533);
                  if (defined_attr(0)) {  /* R.2:0.1:1.0:0.0:1.0 */
                    if (double_attr(0) <= 22.5) {
                      add_pred(   /* R.2:0.1:1.0:0.0:1.0:0 */
                                 -2.0786735515822676);
                    } else {
                      add_pred(   /* R.2:0.1:1.0:0.0:1.0:1 */
                                 0.3864625544983725);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.2:0.1:1.0:1 */
                         0.5541111945860886);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.2:1 */
                 1.6282016222940217);
      if (defined_attr(1)) {  /* R.2:1.0 */
        if (double_attr(1) <= 19.5) {
          add_pred(   /* R.2:1.0:0 */
                     0.6047273555754145);
        } else {
          add_pred(   /* R.2:1.0:1 */
                     -1.2648386268994878);
          if (defined_attr(0)) {  /* R.2:1.0:1.0 */
            if (double_attr(0) <= 60.5) {
              add_pred(   /* R.2:1.0:1.0:0 */
                         -2.259683619673883);
            } else {
              add_pred(   /* R.2:1.0:1.0:1 */
                         1.7547933055294014);
            }
          }
        }
      }
    }
  }
  return finalize_pred();
}
